In [33]:
import pandas as pd
from pandas import Series, DataFrame

In [34]:
import numpy as np
from numpy.random import randn
import os
import matplotlib.pyplot as plt
""" from myfunctions import * """
np.random.seed(12345) #随机种子设置
plt.rc('figure', figsize=(10, 6)) #设置图片放置的格式
np.set_printoptions(precision=4) #四位有效数字

In [35]:
class side_by_side():
    def __init__(self, *frames):
        self.frames = frames

    def _repr_html_(self):
        width = 100. / len(self.frames)

        s = ""
        for f in self.frames:
            s += "<div style='float: left; border-left : 5px solid #6699cc;'>%s</div>" % f._repr_html_()

        return s

In [36]:
obj = Series([100,99,100,60])
print(obj,'\n\n',obj.values,'\n\n',obj.index)

0    100
1     99
2    100
3     60
dtype: int64 

 [100  99 100  60] 

 RangeIndex(start=0, stop=4, step=1)


In [37]:
obj2=Series([4,7,-5,3],index=['d','a','b','c'])
print(obj2,'\n')
print(obj2['a'],'\n')
print(obj2[['c','a']],'\n')

print(obj2 >0,'\n')
print(obj2[obj2>0])

d    4
a    7
b   -5
c    3
dtype: int64 

7 

c    3
a    7
dtype: int64 

d     True
a     True
b    False
c     True
dtype: bool 

d    4
a    7
c    3
dtype: int64


In [38]:
obj2

d    4
a    7
b   -5
c    3
dtype: int64

In [39]:
6 in obj2#索引的是value，而不是index

False

In [40]:
'b' in obj2

True

In [41]:
['b' in obj2.index, 6 in obj2.values]

[True, False]

In [42]:
#直接利用字典来构建Series
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000} #dictionary
obj3=Series(sdata)
print(obj3)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64


In [43]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index=states)#states里面的所有都会进入obj4的Index，但是如果在字典sdata的对应Index不存在，在obj4中对应的value就是NaN
print(obj4)

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64


In [44]:
#通过isnull来判断是都有缺失值
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [45]:
#计算时会自动对齐
print(obj3,'\n\n',obj4,'\n\n',obj3+obj4,'\n')

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64 

 California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64 

 California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64 



In [46]:
print(obj)
#修改index
obj.index=['Tom','a','b','c']
print('\n',obj)

0    100
1     99
2    100
3     60
dtype: int64

 Tom    100
a       99
b      100
c       60
dtype: int64


In [47]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}#list作为dictionary中的value
print(data,end='\n\n')
frame = DataFrame(data) # Create a Dataframe 
frame #没有指定行的index，采用默认值

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}



state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [48]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                   index=['one', 'two', 'three', 'four', 'five'])
print(frame2,'\n')
print(frame2['state'],'\n')
print(frame2.state,'\n')
print(frame.year,'\n')

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN 

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object 

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object 

0    2000
1    2001
2    2002
3    2001
4    2002
Name: year, dtype: int64 



In [49]:
print(frame2,'\n')
print(frame2.loc['three'],'\n')#获取输入的index所对应的行
print(frame2.loc['one'],'\n')

print(frame2.iloc[3])#完全根据行的位置（数）来引用

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN 

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object 

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object 

year       2001
state    Nevada
pop         2.4
debt        NaN
Name: four, dtype: object


In [50]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [51]:
frame2['debt']=16.99#默认为是对列进赋值
frame2

year   state  pop   debt
one    2000    Ohio  1.5  16.99
two    2001    Ohio  1.7  16.99
three  2002    Ohio  3.6  16.99
four   2001  Nevada  2.4  16.99
five   2002  Nevada  2.9  16.99

In [52]:
a=np.arange(5)#使用ndarray进行赋值
print(a,'\n')
frame2['debt']=a
frame2

[0 1 2 3 4] 



year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4

In [53]:
random_col=np.random.randint(100,size=len(frame2))
frame2.insert(3,'random_col',random_col)
frame2

year   state  pop  random_col  debt
one    2000    Ohio  1.5          98     0
two    2001    Ohio  1.7          29     1
three  2002    Ohio  3.6           1     2
four   2001  Nevada  2.4          36     3
five   2002  Nevada  2.9          41     4

In [54]:
del frame2['pop']
frame2.columns
frame2

year   state  random_col  debt
one    2000    Ohio          98     0
two    2001    Ohio          29     1
three  2002    Ohio           1     2
four   2001  Nevada          36     3
five   2002  Nevada          41     4

# important

In [55]:
data = DataFrame({'Qu1': [1, 3, 4, 3, 4],
                  'Qu2': [2, 3, 1, 2, 3],
                  'Qu3': [1, 5, 2, 4,5]})
# 计算各个数出现的频数,按列???
result = data.apply(pd.value_counts,axis=1)
#把function pd.value_counts 按照 axis=1(行) 作用于
side_by_side(data,result)

# 数据合并

## 按照列来合并

In [56]:
from pandas import Series, DataFrame
import pandas as pd
from numpy.random import randn
import numpy as np
from myfunctions import *
np.set_printoptions(precision=4)

按照列进行合并
> pandas.merge

In [57]:
df1 = DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                 'data1': range(7)})
df2 = DataFrame({'key': ['a', 'b', 'd'],
                 'data2': range(3)})
merge1=pd.merge(df1,df2)
side_by_side(df1,df2,merge1)
#说明如果不去通过选项on去指定使用merge去形成新的dataframe的键(key)，默认值就是：将多个数据中重叠的列作为key，进行连接

#默认值：新的Dataframe中的key得是两个旧的Dtaframe中的重叠的key

In [58]:
side_by_side(df1,df2)

In [59]:
#我们可以通过on的指令来指定合并index
dfmerge1=pd.merge(df1,df2,on='key')
#on : label or list
    #Column or index level names to join on. These must be found in #both DataFrames. If `on` is None and not merging on indexes then #this defaults
    #to the intersection of the columns in both DataFrames.
#使得df1和df2按照colunm 'key'进行合并，如果on没有接收到输入，就按照两个Dataframe所共有的列的名称来作为默认值
side_by_side(df1,df2,dfmerge1)


In [60]:
dfmerge2=pd.merge(df1, df2, on='key',how="left")
#how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
    #Type of merge to be performed.

    #* left: use only keys from left frame, similar to a SQL left #outer join;
    #  preserve key order.
    #* right: use only keys from right frame, similar to a SQL right #outer join;
    #  preserve key order.
    #* outer: use union of keys from both frames, similar to a SQL #full outer
    #  join; sort keys lexicographically.
    #* inner: use intersection of keys from both frames, similar to a #SQL inner
    # join; preserve the order of the left keys.
    #* cross: creates the cartesian product from both frames, preserves the order
    #  of the left keys.

    #  .. versionadded:: 1.2.0

#也就是说：将df1和df2按照列'key'进行合并的时候，只使用左边的key中的元素去合并
side_by_side(df1,df2,dfmerge2)
#默认值是inner,也就是左边的df1的key的所有值和右边的df2的key的所有值的交集

In [61]:
dfmerge3=pd.merge(df1, df2, on='key',how="outer")
#* outer: use union of keys from both frames, similar to a SQL #full outer
#取的是并集
side_by_side(df1,df2,dfmerge3)

In [62]:
print('可爱捏')
side_by_side(df1,df2,dfmerge1,dfmerge2,dfmerge3)

可爱捏


In [63]:
df1 = DataFrame({'key': ['b', 'b'],
                 'data1': range(2)})
df2 = DataFrame({'key': ['b',  'b' ],
                 'data2': range(2)})
side_by_side(df1,df2)

In [64]:
merge4=pd.merge(df1,df2,on='key',how='inner')
side_by_side(df1,df2,merge4)
#相当于是说，当我选定初始的key中的某个元素的时候，比如说df1的key的第一个b，他会将这个b与df2中所有的b进行连接

In [65]:
left = DataFrame({'key1': ['foo', 'foo', 'bar'],
                  'key2': ['one', 'two', 'one'],
                  'lval': [1, 2, 3]})
right = DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                   'key2': ['one', 'one', 'one', 'two'],
                   'rval': [4, 5, 6, 7]})
side_by_side(left,right)
#有两种key！

In [66]:
merge5=pd.merge(left,right,on=['key1','key2'],how='outer')
#多个key, 但也可以只去选定一个进行合并
side_by_side(left,right,merge5)
#on : label or list
    #Column or index level names to join on. These must be found in both
    #DataFrames. If `on` is None and not merging on indexes then this defaults
    #to the intersection of the columns in both DataFrames.

In [67]:
"""
left_on : label or list, or array-like
    Column or index level names to join on in the left DataFrame. Can also
    be an array or list of arrays of the length of the left DataFrame.
    These arrays are treated as if they are columns.
right_on : label or list, or array-like
    Column or index level names to join on in the right DataFrame. Can also
    be an array or list of arrays of the length of the right DataFrame.
    These arrays are treated as if they are columns.
left_index : bool, default False
    Use the index from the left DataFrame as the join key(s). If it is a
    MultiIndex, the number of keys in the other DataFrame (either the index
    or a number of columns) must match the number of levels.
right_index : bool, default False
    Use the index from the right DataFrame as the join key. Same caveats as
    left_index.
"""
left1 = DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                  'value': range(6)})
right1 = DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])
side_by_side(left1,right1)

In [81]:
merg1=pd.merge(left1,right1,left_on='key',right_index=True)
side_by_side(left1,right1,merg1)
#左边的Dataframe使用key，右边的Index标定为True之后会含有True
#即左右两边的键名称不同的时候，可以指定

## 按照行来合并（轴向链接）

+ numpy中数组连接 np.concatenate
+ pandas中concat

In [41]:
arr=np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
print(np.concatenate([arr,arr],axis=0),'\n')#按照行叠起来
print(np.concatenate([arr,arr],axis=1))#按照行叠起来

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [50]:
s1 = Series([0, 1], index=['a', 'b'])
s2 = Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = Series([5, 6], index=['f', 'g'])
print(s1,'\n\n',s2,'\n\n',s3,'\n\n')

a    0
b    1
dtype: int64 

 c    2
d    3
e    4
dtype: int64 

 f    5
g    6
dtype: int64 




In [53]:
a=pd.concat([s1,s2,s3],axis=0)
print(a,'\n')#axis=0，默认为按照行叠起来，生成Series
b=pd.concat([s1,s2,s3],axis=1)
print(b)#axis=1，也是按照行叠起来，但是生成的是Dataframe

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64 

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0


In [57]:
df1=DataFrame(np.arange(6).reshape(3,2),index=['a','b','c'],columns=['three','four'])
df2=DataFrame(5+np.arange(4).reshape(2,2),index=['a','c'],columns=['three','four'])
side_by_side(df1,df2)

In [58]:
pd.concat([df1,df2],axis=1,sort=False)

three  four  three  four
a      0     1    5.0   6.0
b      2     3    NaN   NaN
c      4     5    7.0   8.0

In [60]:
data = DataFrame({'k1': ['one'] * 3 + ['two'] * 4,
                  'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  one   1
2  one   2
3  two   3
4  two   3
5  two   4
6  two   4

In [61]:
newdata1=data.drop_duplicates()#去掉重复数据
side_by_side(data,newdata1)

In [63]:
data['v1']=range(7)
print(data)#指出data中将要用于判断的列
newdata2=data.drop_duplicates(['k1'])#只对于k1列进行排序
newdata3=data.drop_duplicates(['k1','k2'],keep='first')
newdata4=data.drop_duplicates(['k1','k2'],keep='last')
side_by_side(data,newdata2,newdata3,newdata4)

    k1  k2  v1
0  one   1   0
1  one   1   1
2  one   2   2
3  two   3   3
4  two   3   4
5  two   4   5
6  two   4   6


# 数据的分组统计和计算
+ 对数据进行分组统计和计算
+ 使用groupby方法

可以归纳出的程序化操作
+ 先试用groupby进行分组操作
+ 然后进行mean等分析计算

In [68]:
df = DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                'key2' : ['one', 'two', 'one', 'two', 'one'],
                'data1' : np.random.randn(5),
                'data2' : np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one -0.007799  0.575721
1    a  two -0.449204  1.381918
2    b  one  2.448963  0.000992
3    b  two  0.667226 -0.143492
4    a  one  0.802926 -0.206282

In [79]:
grouped=df['data1'].groupby(df['key1'])
#对于列'data1'按照'key1'进行分组,但是似乎找不到分组之后的输出？？？
print(DataFrame(grouped),'\n\n\n')
means1=grouped.mean()
print(means1)#只是求了data1关于key1分组之后的各组的平均值

   0                                                  1
0  a  0   -0.007799
1   -0.449204
4    0.802926
Name...
1  b  2    2.448963
3    0.667226
Name: data1, dtype... 



key1
a    0.115308
b    1.558094
Name: data1, dtype: float64


In [84]:
#可以按照多列进行分组
print(df,'\n\n')
means2=df['data1'].groupby([df['key1'],df['key2']]).mean()
print(means2,'\n\n')
#先按照key1进行分组，再按照key2进行分组
means3=df['data1'].groupby([df['key2'],df['key1']]).mean()
print(means3)
#先按照key2进行分组，再按照key1进行分组

  key1 key2     data1     data2
0    a  one -0.007799  0.575721
1    a  two -0.449204  1.381918
2    b  one  2.448963  0.000992
3    b  two  0.667226 -0.143492
4    a  one  0.802926 -0.206282 


key1  key2
a     one     0.397563
      two    -0.449204
b     one     2.448963
      two     0.667226
Name: data1, dtype: float64 


key2  key1
one   a       0.397563
      b       2.448963
two   a      -0.449204
      b       0.667226
Name: data1, dtype: float64


+ 层级化的索引，means，使用unstack来转化成Dataframe

In [87]:
print(means2.unstack(),'\n')
print(means3.unstack(),'\n')

key2       one       two
key1                    
a     0.397563 -0.449204
b     2.448963  0.667226 

key1         a         b
key2                    
one   0.397563  2.448963
two  -0.449204  0.667226 



In [90]:
res1=df.groupby(['key1','key2']).mean()
side_by_side(df,res1)

In [91]:
side_by_side(df,res1.unstack())

In [92]:
df

key1 key2     data1     data2
0    a  one -0.007799  0.575721
1    a  two -0.449204  1.381918
2    b  one  2.448963  0.000992
3    b  two  0.667226 -0.143492
4    a  one  0.802926 -0.206282

In [93]:
df.groupby(['key1','key2'])[['data2']].mean()
#只去选取某些列进行计算

data2
key1 key2          
a    one   0.184720
     two   1.381918
b    one   0.000992
     two  -0.143492

In [94]:
df.groupby(['key1','key2'])[['data2']].mean().unstack()

data2          
key2       one       two
key1                    
a     0.184720  1.381918
b     0.000992 -0.143492

In [96]:
df

key1 key2     data1     data2
0    a  one -0.007799  0.575721
1    a  two -0.449204  1.381918
2    b  one  2.448963  0.000992
3    b  two  0.667226 -0.143492
4    a  one  0.802926 -0.206282

In [99]:
grouped=df.groupby('key1')
grouped['data1'].quantile(0.9)

key1
a    0.640781
b    2.270789
Name: data1, dtype: float64

In [100]:
def peak_to_peak(arr):
    return arr.max() - arr.min()

In [101]:
grouped.agg(peak_to_peak)

C:\Users\16017\AppData\Local\Temp\ipykernel_17088\4193407341.py:1: FutureWarning: ['key2'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  grouped.agg(peak_to_peak)


data1     data2
key1                    
a     1.252129  1.588200
b     1.781737  0.144485

In [106]:
#为什么上面会输出警告呢？
for i,item in grouped:
    print(item)
#输出groupby返回值的内容的一种方式
print('\n\n')
for i in grouped:
    print(i)
#输出值说明，groupby的返回值是以一个又一个二元组，第一个是按照什么排序的key，第二个是一个完整的DataFrame，即按照前面的key聚集在一起组成的DataFrame

#说明使用groupby虽然是对key1进行分组的，但是也保留了key2

  key1 key2     data1     data2
0    a  one -0.007799  0.575721
1    a  two -0.449204  1.381918
4    a  one  0.802926 -0.206282
  key1 key2     data1     data2
2    b  one  2.448963  0.000992
3    b  two  0.667226 -0.143492



('a',   key1 key2     data1     data2
0    a  one -0.007799  0.575721
1    a  two -0.449204  1.381918
4    a  one  0.802926 -0.206282)
('b',   key1 key2     data1     data2
2    b  one  2.448963  0.000992
3    b  two  0.667226 -0.143492)


In [107]:
stocks=pd.read_csv('C:/Users/16017/Desktop/Dropbox/Guide_to_financial_data_analysis/金融数据分析导引/data/A1.csv',encoding='gbk',na_values=['--  '],skiprows=[2781])
substocks=stocks.iloc[:,:13]#根据位置来取切片
substocks

代码     名称  收入同比%%  利润同比%%  营业利润率%%     市销率    市净率     市现率   市盈(动)  \
0          1   平安银行   34.09   15.02    32.78    3.64   1.12    0.93    7.31   
1          2  万  科Ａ   22.72    0.77    17.35    3.13   1.80  -23.08   16.21   
2          4   国农科技  117.08  125.75    10.98   36.85  26.93 -337.10  905.17   
3          5   世纪星源   52.10    8.05   -64.57  148.17   8.32  155.10     NaN   
4          6   深振业Ａ  311.53  425.18    17.93    6.29   3.01  -20.19   24.66   
...      ...    ...     ...     ...      ...     ...    ...     ...     ...   
2775  603989   艾华集团    0.00    0.00    18.72   11.11   3.71   75.26   37.25   
2776  603993   洛阳钼业  -38.77  -53.92    19.07   30.36   4.43   55.15   74.40   
2777  603997   继峰股份    0.00    0.00    20.07   12.11   4.87   53.97   34.88   
2778  603998   方盛制药   14.86   12.48    26.95   19.08   5.18  128.87   45.80   
2779  600656  *ST博元    0.00 -874.28      NaN    0.00   0.00    0.00     NaN   

               总金额    量比  细分行业  地区  
0     3.273803e+09  1.40    银行  深圳  
1     3.218100e+09  1.33  全国地产  深圳  
2     1.750940e+08  0.79  生物制药  深圳  
3     0.000000e+00  0.00  区域地产  深圳  
4     5.046951e+08  0.82  区域地产  深圳  
...            ...   ...   ...  ..  
2775  9.135913e+07  0.61   NaN  湖南  
2776  1.251790e+09  1.05   NaN  河南  
2777  4.854032e+07  0.57   NaN  浙江  
2778  2.782407e+08  1.94   NaN  湖南  
2779           NaN  0.00   综合类  广东  

[2780 rows x 13 columns]

In [108]:
substocks.head()#输出最开始的前多少行，默认值是5行

代码     名称  收入同比%%  利润同比%%  营业利润率%%     市销率    市净率     市现率   市盈(动)  \
0   1   平安银行   34.09   15.02    32.78    3.64   1.12    0.93    7.31   
1   2  万  科Ａ   22.72    0.77    17.35    3.13   1.80  -23.08   16.21   
2   4   国农科技  117.08  125.75    10.98   36.85  26.93 -337.10  905.17   
3   5   世纪星源   52.10    8.05   -64.57  148.17   8.32  155.10     NaN   
4   6   深振业Ａ  311.53  425.18    17.93    6.29   3.01  -20.19   24.66   

            总金额    量比  细分行业  地区  
0  3.273803e+09  1.40    银行  深圳  
1  3.218100e+09  1.33  全国地产  深圳  
2  1.750940e+08  0.79  生物制药  深圳  
3  0.000000e+00  0.00  区域地产  深圳  
4  5.046951e+08  0.82  区域地产  深圳

In [109]:
substocks.columns
#想修改名称

Index(['代码', '名称', '收入同比%%', '利润同比%%', '营业利润率%%', '市销率', '市净率', '市现率', '市盈(动)',
       '总金额', '量比', '细分行业', '地区'],
      dtype='object')

In [111]:
substocks.columns=map(lambda x: 'F'+str(x), range(13))
substocks.head()

F0     F1      F2      F3     F4      F5     F6      F7      F8  \
0   1   平安银行   34.09   15.02  32.78    3.64   1.12    0.93    7.31   
1   2  万  科Ａ   22.72    0.77  17.35    3.13   1.80  -23.08   16.21   
2   4   国农科技  117.08  125.75  10.98   36.85  26.93 -337.10  905.17   
3   5   世纪星源   52.10    8.05 -64.57  148.17   8.32  155.10     NaN   
4   6   深振业Ａ  311.53  425.18  17.93    6.29   3.01  -20.19   24.66   

             F9   F10   F11 F12  
0  3.273803e+09  1.40    银行  深圳  
1  3.218100e+09  1.33  全国地产  深圳  
2  1.750940e+08  0.79  生物制药  深圳  
3  0.000000e+00  0.00  区域地产  深圳  
4  5.046951e+08  0.82  区域地产  深圳

In [124]:
grouped = substocks.groupby('F12')
for i in grouped:
    print(i)

('上海',           F0     F1     F2      F3      F4       F5     F6      F7       F8  \
227      668   荣丰控股 -22.99   85.15 -555.93  1145.69   8.25  -40.97      NaN   
363      863   三湘股份 -67.99  130.61   35.01    41.02   2.90   -4.28    50.50   
487     2022   科华生物  -3.67  -19.76   23.66    16.66   7.08   92.57    38.63   
493     2028   思源电气  20.08    2.74   10.88     4.98   2.05  -58.84    26.76   
523     2058  威 尔 泰 -13.71 -627.60  -18.55    62.62  13.42 -204.02      NaN   
...      ...    ...    ...     ...     ...      ...    ...     ...      ...   
2751  603718   海利生物   0.00    0.00   39.59    43.56   7.45   84.77    62.25   
2752  603729   龙韵股份   0.00    0.00    4.35     7.38   5.31  -28.02    72.88   
2764  603885   吉祥航空   0.00    0.00   16.64     6.33   7.66   23.11    23.51   
2767  603899   晨光文具   0.00    0.00   12.96     7.66   7.24   54.06    34.11   
2769  603918   金桥信息   0.00    0.00    0.09    13.12   6.01  -26.81  4925.10   

               F9   F10   F11 F12  
227     

In [125]:
results=grouped.describe()
results.head()

F0                                                            \
     count           mean            std    min        25%       50%   
F12                                                                    
上海   219.0  470839.981735  216423.913350  668.0  300326.50  600610.0   
云南    30.0  251143.666667  295172.840070  538.0    1228.25    2577.5   
内蒙    25.0  396636.480000  269704.076381  426.0    2688.00  600111.0   
北京   259.0  347354.046332  245993.041606   10.0    2717.00  300379.0   
吉林    40.0  285930.725000  295532.904000   30.0     754.00  151365.0   

                             F2             ...           F9                \
           75%       max  count       mean  ...          75%           max   
F12                                         ...                              
上海   600760.50  603918.0  219.0  33.327352  ...  464146000.0  6.734183e+09   
云南   600449.75  601099.0   30.0  12.088667  ...  238602028.0  9.376749e+08   
内蒙   600295.00  601216.0   25.0   2.376400  ...  217340496.0  2.701873e+09   
北京   600580.00  603979.0  259.0  23.082008  ...  511800688.0  7.802157e+09   
吉林   600381.75  603099.0   40.0  40.845000  ...  306623152.0  1.177235e+09   

       F10                                                        
     count      mean       std  min     25%    50%     75%   max  
F12                                                               
上海   219.0  0.799772  0.452698  0.0  0.6600  0.820  1.0850  2.21  
云南    30.0  0.665000  0.394407  0.0  0.5875  0.705  0.8175  1.78  
内蒙    25.0  0.704800  0.509093  0.0  0.0200  0.780  0.9800  1.65  
北京   259.0  0.847606  0.461970  0.0  0.6800  0.860  1.0500  2.45  
吉林    40.0  0.628000  0.371243  0.0  0.5800  0.735  0.8800  1.21  

[5 rows x 80 columns]

In [127]:
results.unstack()

            F12
F0   count  上海     219.00
            云南      30.00
            内蒙      25.00
            北京     259.00
            吉林      40.00
                    ...  
F10  max    辽宁       3.30
            重庆       1.55
            陕西       1.48
            青海       1.40
            黑龙江      1.49
Length: 2560, dtype: float64

In [122]:
results['F2'].unstack()

       F12
count  上海      219.00
       云南       30.00
       内蒙       25.00
       北京      259.00
       吉林       40.00
               ...   
max    辽宁      174.53
       重庆      300.89
       陕西     1032.27
       青海       25.45
       黑龙江      53.70
Length: 256, dtype: float64