In [156]:
from numpy.random import randn #产生正态随机数的函数
import numpy as np #简便书写

In [157]:
np.array([3.4, 5.5])#生成array 数据的函数

array([3.4, 5.5])

In [158]:
data = randn(2,3)
print(data)
print(data.shape) #输出array格式的数据的维数
print(data.dtype) #输出array格式的的数据的类别
b = [[2,]]
np.array(b).shape #说明空的会被省略掉

[[ 0.3192411  -0.67316001  1.13375406]
 [ 0.17912702  1.98246491 -1.35834762]]
(2, 3)
float64


(1, 1)

In [159]:
a=np.array([1,2,3])
b=np.array([[1,]])
c=np.array([[1,0,0],[0,1,2]])
print(a,a.shape,a.dtype,end='\n\n')
print(b,b.shape,b.dtype,end='\n\n')
print(c,c.shape,c.dtype,end='\n\n')

[1 2 3] (3,) int32

[[1]] (1, 1) int32

[[1 0 0]
 [0 1 2]] (2, 3) int32



In [160]:
print(np.arange(15),end='\n\n') #输出等差数列，默认值0-15，不包含mxa=15，默认步长为1
print(np.arange(2,15),end='\n\n') #输出等差数列，从2-15，不包含15，默认步长为1
print(np.arange(2,15,2),end='\n\n') #输出等差数列，从2-15，不包含15，步长设定为2
print(np.arange(2,15,1.5),end='\n\n') #步长设定为1.5

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 2  4  6  8 10 12 14]

[ 2.   3.5  5.   6.5  8.   9.5 11.  12.5 14. ]



In [161]:
print(np.linspace(0,1,11),end='\n\n')#从0-11，不包含11，设定一共有11个
print(np.linspace(0,1,11, endpoint = False), end='\n\n')
print(np.linspace(0,1,11, endpoint = True), end='\n\n')#可以设置是否包含max
print(np.linspace(0,1,12),end='\n\n')

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]



In [162]:
data1=[6,7.8,8.9,33]
arr1=np.array(data1)
print(arr1,arr1.shape,arr1.dtype)

[ 6.   7.8  8.9 33. ] (4,) float64


In [163]:
data2=[[1,2,3.0,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2,arr2.shape,arr2.dtype)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]] (2, 4) float64


In [164]:
#使用reshape来改变维数
print(arr2,arr2.shape,arr2.dtype,end='\n\n')
b=arr2.reshape((1,8))
print(b,b.shape,b.dtype,end='\n\n')
b=arr2.reshape((4,2))
print(b,b.shape,b.dtype,end='\n\n')


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]] (2, 4) float64

[[1. 2. 3. 4. 5. 6. 7. 8.]] (1, 8) float64

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]] (4, 2) float64



In [165]:
a=np.zeros(10,dtype='int')
print(a,a.shape,a.dtype)
a=np.zeros(10,dtype='float')
print(a,a.shape,a.dtype)

[0 0 0 0 0 0 0 0 0 0] (10,) int32
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,) float64


In [166]:
b=np.ones((2,3),dtype='int')
print(b,b.shape,b.dtype)
b=np.ones((2,3),dtype='float')
print(b,b.shape,b.dtype)

[[1 1 1]
 [1 1 1]] (2, 3) int32
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3) float64


In [167]:
c=np.identity(2)#单位矩阵(方阵)
print(c,c.shape,c.dtype,end='\n\n')
d=np.eye(4,9)
print(d,d.shape,d.dtype)

[[1. 0.]
 [0. 1.]] (2, 2) float64

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]] (4, 9) float64


In [168]:
arr = np.array([1,2,3,4,5],dtype=np.int32)
print(arr,arr.shape,arr.dtype)

[1 2 3 4 5] (5,) int32


In [169]:
#使用astype去修改类型
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.shape,float_arr.dtype)

[1. 2. 3. 4. 5.] (5,) float64


In [170]:
arr=np.array([3.7,1.2,0.5,12.7,5.6])
c=arr.astype(np.int32)
print(c,c.shape,c.dtype)

[ 3  1  0 12  5] (5,) int32


In [171]:
c=numeric_strings = np.array(['1.25', '42'],dtype=str)
print(c,c.shape,c.dtype)
c=c.astype(float)
print(c,c.shape,c.dtype)

['1.25' '42'] (2,) <U4
[ 1.25 42.  ] (2,) float64


In [172]:
arr=np.array(([1,2,3],[4,5,6]),dtype=float)
print(arr,end='\n\n')
print(arr*arr,end='\n\n')#对应元素相乘
print(arr*arr-arr,end='\n\n')
print(1/arr,end='\n\n')
print(arr*2,end='\n\n')
print(arr**2,end='\n\n')#对应元素平方

[[1. 2. 3.]
 [4. 5. 6.]]

[[ 1.  4.  9.]
 [16. 25. 36.]]

[[ 0.  2.  6.]
 [12. 20. 30.]]

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]]

[[ 1.  4.  9.]
 [16. 25. 36.]]



In [173]:
arr=np.arange(10)
print(arr,arr.shape,arr.dtype)
print(arr[5:8])
arr[5:8] = 12
print(arr,arr.shape,arr.dtype)

[0 1 2 3 4 5 6 7 8 9] (10,) int32
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9] (10,) int32


In [174]:
arr=np.arange(10)
arr_slice=arr[5:8]
print(id(arr_slice), id(arr[5:8]),)
print(arr_slice is arr[5:8],'\n',arr_slice == arr[5:8] )
arr_slice[1]=12345
print(arr,'\n', arr_slice)

2177491970992 2177465975792
False 
 [ True  True  True]
[    0     1     2     3     4     5 12345     7     8     9] 
 [    5 12345     7]


原因：
> object（对象） 与 location（地址） 并不相同
+ 一个对象可以是一个指针，例如对象A是个指针，它的内容是->B，其中B是一个存储空间；C也可以是个指针，内容也是->B，这时候它们是两个不同的对象，指向同一个存储空间
> 但实际上，切片slice，只是创造了一个视图，其实指向的地址还是不一样

In [175]:
print(arr,'\n',arr_slice)
arr_slice[:]=64
print(arr,'\n',arr_slice)

[    0     1     2     3     4     5 12345     7     8     9] 
 [    5 12345     7]
[ 0  1  2  3  4 64 64 64  8  9] 
 [64 64 64]


In [176]:
a_list=list(range(10))
list_slice=a_list[5:8]
print(a_list is list_slice)
list_slice[1] = 12345
print(a_list, '\n', list_slice)

False
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
 [5, 12345, 7]


In [177]:
a=[1,2,3,[1,2]]
b=a[3][1]
print(b is a[3][1])
b=1000
print(a,'\n',b)

True
[1, 2, 3, [1, 2]] 
 1000


In [178]:
import copy
c=copy.deepcopy(a)
print(a is c, a==c)

False True


In [179]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d,arr2d.shape,arr2d.dtype,end='\n\n')
print(arr2d,'\n\n',arr2d[0],'\n\n',arr2d[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) int32

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [1 2 3] 

 2


In [180]:
print(arr2d,end='\n\n')
print(arr2d[:][0] , '\n\n', arr2d[:,0],end='\n\n')
print(arr2d[:][0]==arr2d[:,0], arr2d[:][0] is arr2d[:,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3] 

 [1 4 7]

[ True False False] False


+ arr2d[:][0] is equivalent to arr2d[0] instead of arr2d[:,0]

In [181]:
#二维数组切片也传输地址
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d,end='\n\n')
b = arr2d[2]
print(b,b is arr2d[2],end='\n\n')
arr2d[2] = 3
print('arr2d[2]=',arr2d[2],'\n\n','arr2d=\n',arr2d,end='\n\n')
#二维数组的切片一定会传地址
c=arr2d[0][:2]
print(c is arr2d[0][:2], c, end='\n\n')
arr2d[0][:2]=1000
print('arr2d[0][:2]=',arr2d[0][:2],'\n','arr2d=\n',arr2d,end='\n\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[7 8 9] False

arr2d[2]= [3 3 3] 

 arr2d=
 [[1 2 3]
 [4 5 6]
 [3 3 3]]

False [1 2]

arr2d[0][:2]= [1000 1000] 
 arr2d=
 [[1000 1000    3]
 [   4    5    6]
 [   3    3    3]]



In [182]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d,'\n\n',arr3d.shape,'\n\n',arr3d.dtype)
print('arr3d[0]=',arr3d[0])
print('arr3d[0][0]=',arr3d[0][0])
print('arr3d[0][0][0]=',arr3d[0][0][0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

 (2, 2, 3) 

 int32
arr3d[0]= [[1 2 3]
 [4 5 6]]
arr3d[0][0]= [1 2 3]
arr3d[0][0][0]= 1


+ 数组拷贝
> 要生成新的对象(传递数值)，而不是传递地址，需要用到copy函数

In [183]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d,arr2d.shape,arr2d.dtype,end='\n\n')

old_values=arr2d.copy()
old_1=copy.deepcopy(arr2d)
print(old_values)

arr2d[0][:]=999
print(arr2d,'\n',old_values,'\n',old_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) int32

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[999 999 999]
 [  4   5   6]
 [  7   8   9]] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [184]:
print(arr)
print(arr[1:6],'\n')

print(arr2d)
print(arr2d[:2],'\n')

print(arr2d[1, :2],'\n')

arr2d[:2 , 1: ]=0
print(arr2d)

[ 0  1  2  3  4 64 64 64  8  9]
[ 1  2  3  4 64] 

[[999 999 999]
 [  4   5   6]
 [  7   8   9]]
[[999 999 999]
 [  4   5   6]] 

[4 5] 

[[999   0   0]
 [  4   0   0]
 [  7   8   9]]


In [185]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = randn(7,4)
print(names,'\n\n',data,'\n')

print(names == 'Bob','\n') #返回的逻辑判断是对所有元素逐个判断之后合并起来的array变量
print(data[names == 'Bob'],'\n')#输出的是取了True的行，其他都没有输出
print(data[names == 'Bob',2:],'\n')#第三列到最后
print(data[names == 'Bob',3:],'\n')#第四列

print(names != 'Bob')
print(data[names != 'Bob'],'\n')

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] 

 [[-0.17872588 -0.25569421  0.56120059 -1.22199587]
 [-0.92460662 -0.58359025 -0.19233456  0.54893941]
 [ 0.29801744  0.48836221  1.60763441  0.81107404]
 [ 1.08536569  0.63556861  0.63352529 -0.92164713]
 [-0.85851877  1.61867532 -1.46538398  0.74410527]
 [-0.42675704  0.36538623  0.15421803  0.15693241]
 [-0.73011664  0.80600366  0.21969491 -1.01815037]] 

[ True False False  True False False False] 

[[-0.17872588 -0.25569421  0.56120059 -1.22199587]
 [ 1.08536569  0.63556861  0.63352529 -0.92164713]] 

[[ 0.56120059 -1.22199587]
 [ 0.63352529 -0.92164713]] 

[[-1.22199587]
 [-0.92164713]] 

[False  True  True False  True  True  True]
[[-0.92460662 -0.58359025 -0.19233456  0.54893941]
 [ 0.29801744  0.48836221  1.60763441  0.81107404]
 [-0.85851877  1.61867532 -1.46538398  0.74410527]
 [-0.42675704  0.36538623  0.15421803  0.15693241]
 [-0.73011664  0.80600366  0.21969491 -1.01815037]] 



In [186]:
mask = (names == 'Bob') | (names == 'Will')  # 还有&
print(mask,'\n')
print(data[mask],'\n')

[ True False  True  True  True False False] 

[[-0.17872588 -0.25569421  0.56120059 -1.22199587]
 [ 0.29801744  0.48836221  1.60763441  0.81107404]
 [ 1.08536569  0.63556861  0.63352529 -0.92164713]
 [-0.85851877  1.61867532 -1.46538398  0.74410527]] 



In [187]:
print(data,'\n')
print(data < 0 ,'\n')

data[data<0] = 0
print ( data,'\n')

[[-0.17872588 -0.25569421  0.56120059 -1.22199587]
 [-0.92460662 -0.58359025 -0.19233456  0.54893941]
 [ 0.29801744  0.48836221  1.60763441  0.81107404]
 [ 1.08536569  0.63556861  0.63352529 -0.92164713]
 [-0.85851877  1.61867532 -1.46538398  0.74410527]
 [-0.42675704  0.36538623  0.15421803  0.15693241]
 [-0.73011664  0.80600366  0.21969491 -1.01815037]] 

[[ True  True False  True]
 [ True  True  True False]
 [False False False False]
 [False False False  True]
 [ True False  True False]
 [ True False False False]
 [ True False False  True]] 

[[0.         0.         0.56120059 0.        ]
 [0.         0.         0.         0.54893941]
 [0.29801744 0.48836221 1.60763441 0.81107404]
 [1.08536569 0.63556861 0.63352529 0.        ]
 [0.         1.61867532 0.         0.74410527]
 [0.         0.36538623 0.15421803 0.15693241]
 [0.         0.80600366 0.21969491 0.        ]] 



In [188]:
data [ names != 'Joe'] = 7
print(data)

[[7.         7.         7.         7.        ]
 [0.         0.         0.         0.54893941]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [0.         0.36538623 0.15421803 0.15693241]
 [0.         0.80600366 0.21969491 0.        ]]


In [189]:
np.empty([2,2],dtype=int)

array([[16843009, 16843009],
       [16843009, 16843009]])

+ Keep in mind that the values in the array are essentially garbage values until you explicitly assign values to them.

In [190]:
?np.empty  # 使用 ipython 中的 ? 进行索引说明

Object `np.empty  # 使用 ipython 中的 ? 进行索引说明` not found.


In [191]:
arr = np.empty([8,4])
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [192]:
#可以同时索引多行
arr[[4,5,6,0]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [0., 0., 0., 0.]])

In [193]:
arr[[-1,-2,0,2]] #-1就是倒数第一行，这里是第八行(7)

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [0., 0., 0., 0.],
       [2., 2., 2., 2.]])

In [194]:
arr = np.arange(32).reshape((8,4))
print(arr,'\n')

b = arr[[1,5,7,2]]
print(b,'\n')

c = arr[:,[0,3,1,2]]
print(c,'\n')

d = arr[[1,5,7,2],:][: , [0,3,1,2]]
print(d,'\n')

e = arr[[1,5,7,2],[0,3,1,2]]
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]] 

[[ 0  3  1  2]
 [ 4  7  5  6]
 [ 8 11  9 10]
 [12 15 13 14]
 [16 19 17 18]
 [20 23 21 22]
 [24 27 25 26]
 [28 31 29 30]] 

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]] 

[ 4 23 29 10]


In [195]:
arr=np.arange(15).reshape((3,5))
print(arr,'\n\n',arr.T,'\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] 



In [196]:
arr=np.random.randn(6,3)
np.dot(arr.T, arr)#真正的矩阵乘法

array([[ 5.31793861,  0.29960075,  0.45766063],
       [ 0.29960075,  5.78891428, -1.9058296 ],
       [ 0.45766063, -1.9058296 ,  3.91187592]])

In [197]:
arr = np.arange(16).reshape((2,2,4))
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [198]:
arr = np.arange(10)
print(arr,'\n')
print(np.sqrt(arr),'\n')
print(np.exp(arr),'\n')

[0 1 2 3 4 5 6 7 8 9] 

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03] 



In [199]:
x=randn(8)
y=randn(8)
print(x,y,'\n')
print(np.maximum(x,y))#生成二维元组，对应位置取x,y的最大值

[ 1.59559376  1.9274926  -1.08344231  0.63771828  1.2934025   0.77806739
 -0.13613861 -1.18403072] [-0.59705253 -0.94285944  0.25077418 -1.0432987   0.76569732 -0.21548239
 -0.53145377 -1.44341468] 

[ 1.59559376  1.9274926   0.25077418  0.63771828  1.2934025   0.77806739
 -0.13613861 -1.18403072]


In [200]:
arr = randn(7)*5
print(arr,'\n')
print(np.modf(arr))

print('test:\n')
arr = np.arange(15)+0.67
print('arr=',arr,'\n')
print('np.modf(arr)=',np.modf(arr),'\n')

[ 2.3169992   5.33672161 -1.22389738  3.44357595 -2.57408955 -3.89429947
  0.50162323] 

(array([ 0.3169992 ,  0.33672161, -0.22389738,  0.44357595, -0.57408955,
       -0.89429947,  0.50162323]), array([ 2.,  5., -1.,  3., -2., -3.,  0.]))
test:

arr= [ 0.67  1.67  2.67  3.67  4.67  5.67  6.67  7.67  8.67  9.67 10.67 11.67
 12.67 13.67 14.67] 

np.modf(arr)= (array([0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 0.67,
       0.67, 0.67, 0.67, 0.67]), array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])) 



In [201]:
points = np.arange(-5,5,0.01)
xs,ys = np.meshgrid(points,points)#生成网格

print(ys,'\n')

print(xs,'\n')

[[-5.   -5.   -5.   ... -5.   -5.   -5.  ]
 [-4.99 -4.99 -4.99 ... -4.99 -4.99 -4.99]
 [-4.98 -4.98 -4.98 ... -4.98 -4.98 -4.98]
 ...
 [ 4.97  4.97  4.97 ...  4.97  4.97  4.97]
 [ 4.98  4.98  4.98 ...  4.98  4.98  4.98]
 [ 4.99  4.99  4.99 ...  4.99  4.99  4.99]] 

[[-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 ...
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]
 [-5.   -4.99 -4.98 ...  4.97  4.98  4.99]] 



In [202]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [203]:
result = np.where(cond, xarr, yarr)#condition放在第一个
print(result)

[1.1 2.2 1.3 1.4 2.5]


In [204]:
arr=randn(4,4)
print(arr,'\n')
print(np.where(arr>0 , 2,-2))

print(np.where(arr>0,2,arr))#只有大于2的会改变

[[ 2.23716548  1.05702038 -1.69319386  0.8361549 ]
 [-2.06525477  1.87998311  0.58641227  0.78704777]
 [ 0.68943263 -0.66774698 -0.6992185  -0.88709689]
 [ 0.62290984 -1.34064248  0.63401856 -0.88281804]] 

[[ 2  2 -2  2]
 [-2  2  2  2]
 [ 2 -2 -2 -2]
 [ 2 -2  2 -2]]
[[ 2.          2.         -1.69319386  2.        ]
 [-2.06525477  2.          2.          2.        ]
 [ 2.         -0.66774698 -0.6992185  -0.88709689]
 [ 2.         -1.34064248  2.         -0.88281804]]


In [205]:
arr = np.random.randn(5,4)
print(arr)
print(arr.mean())#求所有元素的平均数
print(arr.sum())#求所有元素的和

[[ 1.32450259 -1.00941953  1.43578502  0.83033906]
 [-0.87164747  0.1258827  -1.08892099 -0.90156244]
 [ 0.72160043 -0.87232091  1.53909366 -0.90927085]
 [ 1.55614154  0.81867135 -0.36080106  0.20691931]
 [-0.20165046 -1.11827404 -1.56190931 -1.27020024]]
-0.08035208281821968
-1.6070416563643934


In [206]:
arr = np.random.randn(5,4)
print(arr)
print(arr.mean())
print(arr.mean(axis=0))#按行求平均值
print(arr.mean(axis=1),'\n')#按列去求平均值
print(arr.sum(axis=0))#按行去求和
print(arr.sum(axis=1))#按列去求和

[[-0.46223377 -0.24404519 -0.02398056  0.37714308]
 [ 2.23967034  1.34709968  1.82132011  0.06120014]
 [ 1.58278614 -0.29997199  0.03389977  1.13107212]
 [ 2.34683536 -0.70770164  1.95636117  1.97753219]
 [ 1.35507633  0.31371426  0.27316598 -1.4640075 ]]
0.6807468007040096
[1.41242688 0.08181902 0.81215329 0.41658801]
[-0.08827911  1.36732256  0.61194651  1.39325677  0.11948727] 

[7.0621344  0.40909512 4.06076646 2.08294004]
[-0.35311644  5.46929026  2.44778604  5.57302709  0.47794907]


In [212]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(arr,'\n')
print(arr.cumsum(0))

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]


In [220]:
arr = randn(100)
print(arr,'\n')
print((arr>0).sum())

[ 2.07007709 -2.69303235  1.46053914  0.20456127 -0.17845922 -0.67172091
 -0.58404964 -1.47812221  1.06730168 -1.06311426 -0.22832272  0.2625817
  0.11890047  1.17509178 -0.74420285  1.29146873  0.95622199 -0.34847173
  1.01380095  1.01661601 -0.44515774 -0.4985426   1.46993628  0.65305314
  0.44100553 -0.69694802  0.94657385  1.83941819 -0.58299143  0.68940818
  1.12668278 -0.51018349  2.21234696  2.08907372  1.25594133 -0.23840061
 -0.03945636 -1.94819371  1.22484395  0.24117936 -1.06227558  0.09437509
 -0.91145693  0.80485054  0.73980808  0.23362754 -0.82945003  2.11048483
  0.98106892  0.47368824 -1.08893145 -0.35770246 -0.23668908  1.15868734
 -0.43342439  1.88776645  1.81749239 -1.04387648  1.94689496  0.58113388
  0.32316201  0.67780484 -1.25776201  0.19541457  0.68661454 -0.58776153
 -2.74601491 -0.09362513  1.51482087  0.69644189 -0.68814841  0.95578558
  0.76135901 -0.27780559  0.56625186 -0.60219215  1.70474584  0.74027291
  0.15666842  1.08703515  1.39266597 -0.47378805 -0.

In [223]:
bools = np.array([False, False, True, False])
print(bools.any())
print(bools.all())

True
False


In [224]:
arr = randn(8)
print(arr,'\n')
x = arr.sort()
print(arr,'\n')
print(x)

[ 0.61310342 -1.60577422  0.33023465 -2.01371434  1.90438638  0.71188584
  2.31931475  0.63984496] 

[-2.01371434 -1.60577422  0.33023465  0.61310342  0.63984496  0.71188584
  1.90438638  2.31931475] 

None


In [225]:
?np.sort

Signature: np.sort(a, axis=-1, kind=None, order=None)
Docstring:
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecif

In [227]:
arr = randn(5,3)
print(arr,'\n')
arr.sort(0)#按照列排序
print(arr)

[[ 0.17145896 -1.52602272  1.5854286 ]
 [ 0.49801416 -0.64500621  1.14538681]
 [ 1.65124163 -1.19610026  0.73750836]
 [-1.55495568  0.30361193 -0.59113717]
 [-1.10052218 -0.96703533 -1.82893308]] 

[[-1.55495568 -1.52602272 -1.82893308]
 [-1.10052218 -1.19610026 -0.59113717]
 [ 0.17145896 -0.96703533  0.73750836]
 [ 0.49801416 -0.64500621  1.14538681]
 [ 1.65124163  0.30361193  1.5854286 ]]


In [228]:
arr = randn(5,3)
print(arr,'\n')
arr.sort(1)
print(arr)

[[ 0.5321423   0.16431801 -0.95005707]
 [-1.38661766 -0.87009503 -0.01135111]
 [-0.66603627 -0.29659678 -0.34695893]
 [ 1.09030618 -0.16802158  1.37154675]
 [-1.07306628  0.01434594  1.02245603]] 

[[-0.95005707  0.16431801  0.5321423 ]
 [-1.38661766 -0.87009503 -0.01135111]
 [-0.66603627 -0.34695893 -0.29659678]
 [-0.16802158  1.09030618  1.37154675]
 [-1.07306628  0.01434594  1.02245603]]


In [231]:
#np.unique()返回所有出现过的元素（次数为一次）
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

['Bob' 'Joe' 'Will']
[1 2 3 4]


In [237]:
print(set(names)) #set 形成集合 set也是一种数据类型
print(np.array(set(names)))
print(sorted(set(names)))

{'Joe', 'Bob', 'Will'}
{'Joe', 'Bob', 'Will'}
['Bob', 'Joe', 'Will']


In [239]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2,3,6])#测试，左边的元素是不是在右边

array([ True, False, False,  True,  True, False,  True])

In [241]:
arr = np.arange(10)
np.save('some_array', arr)
a = np.load('some_array.npy')
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [251]:
x=np.array([[1,2,3],[4,5,6]],dtype=float)
y=np.array([[6,23],[-1,7],[8,9]],dtype=float)
print(x,'\n\n',y,'\n\n',x.shape,y.shape,'\n')
print(x.dot(y),'\n\n', (x.T).dot(y.T),'\n\n')
print(np.dot(x,y),'\n\n',np.dot(x.T,y.T))

[[1. 2. 3.]
 [4. 5. 6.]] 

 [[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]] 

 (2, 3) (3, 2) 

[[ 28.  64.]
 [ 67. 181.]] 

 [[ 98.  27.  44.]
 [127.  33.  61.]
 [156.  39.  78.]] 


[[ 28.  64.]
 [ 67. 181.]] 

 [[ 98.  27.  44.]
 [127.  33.  61.]
 [156.  39.  78.]]


In [255]:
t=np.ones(3)
print(t,'\n')
print(x.shape,t.shape,end='\n\n')
print(np.dot(x,t))

[1. 1. 1.] 

(2, 3) (3,)

[ 6. 15.]


In [261]:
from numpy.linalg import inv, qr
x = randn(5,5)
print('x=\n',x,'\n\n')
mat = (x.T).dot(x)
print('mat=\n',mat,'\n\n')
c=inv(mat)
print('The invert of mat is\n ', c,'\n\n')
(q, r)=qr(mat)
print('q=\n',q,'\n\n')
print('r=\n',r,'\n\n')

x=
 [[-0.3755847  -1.02529964  0.33812979  0.52754975  0.54696716]
 [ 0.12982844  1.58424493  0.04415913 -0.37045732  0.06027039]
 [ 0.47595983 -0.13774299  1.54566752  0.29964252  1.40176556]
 [-0.17330577 -0.44113998  0.43800773 -0.88289319  0.76412782]
 [ 1.70280328 -0.81448733  1.85644254 -1.124569   -0.1933254 ]] 


mat=
 [[ 3.31403094 -0.78525282  3.69965956 -1.86552701  0.00795352]
 [-0.78525282  4.43803858 -2.194902    0.13636134 -0.8380318 ]
 [ 3.69965956 -2.194902    6.14359954 -1.84924286  2.33006727]
 [-1.86552701  0.13636134 -1.84924286  2.54948882  0.22901784]
 [ 0.00795352 -0.8380318   2.33006727  0.22901784  2.88901832]] 


The invert of mat is
  [[ 2.68920021e+01 -3.84637754e+00 -2.44143628e+01  5.16367914e-01
   1.84601036e+01]
 [-3.84637754e+00  8.37546352e-01  3.64018263e+00  2.21859147e-02
  -2.68411889e+00]
 [-2.44143628e+01  3.64018263e+00  2.26216218e+01 -1.13761283e-01
  -1.71127604e+01]
 [ 5.16367914e-01  2.21859147e-02 -1.13761283e-01  6.82541159e-01
   4.265

In [275]:
#生成随机数
smaples = np.random.normal(size=(4,4))
print(smaples)
print(np.mean(smaples))

[[-0.08881692  1.15858193 -1.17933738 -2.13968393]
 [ 0.82144224  2.26854232  0.98145734 -0.7322152 ]
 [-0.35785547 -1.17050115  0.38294671  0.97962245]
 [-0.28756499  0.42724861  0.80425825  1.49452765]]
0.21016577917125742
