
## Numpy

1.  给定一个二维数组，每行是一个向量。找出所有不同的行。
比如： 

```x = np.array([[1., 2., 3.], [4., 5., 6.],[1., 2., 3.], [4., 5., 6.]]),则
x[:2]，即x的第0,1行，array([[ 1.,  2.,  3.],[ 4.,  5.,  6.]])就是要找到行。
```

备注：请不要直接调用numpy.unique

2.  a).产生正态数据数据向量 Z,长度为T， 建立一个二维数组，使其第一行为 (Z[0],Z[1],Z[2])，然后每一行都后移一位 （因此最后一行为 (Z[T-3],Z[T-2],Z[T-1] );b). 计算每列数据的样本均值，方差，各列之间的协方差。
 
3. a). 随机生成一个1000行50列二维数组，每个元素等概率取值0，1，2，并将该数组按第1列递增和第2列递减对每行排序，即先按第一列递增排序，然后在第一列每组中， 按第二列递减排序。 b). 编一个函数sortbycols(data,cols,descending)，实现行排序。给定参数 data是二维数值，cols是数或list,给出需要排序的列，descending是布尔值或布尔向量，如果是一个布尔值，则所有列都按该顺序排，如果descending是和cols等长的list，则各列按descending给定的顺序排。
4.  熟悉学习numpy中的现金流函数, np.pv,np.fv,np.nper,np.pmt,np.rate, 然后编制一个函数，计算给定现金流(array)，利率(array),任意时刻(t)的现金价值。

5. 有一个列表X,里面的元素可能是数，包含数的list,或者数值型np.array。请编一个函数把它转换为一维np.array数据。 比如将X=[[1,[2,[4,9]]],np.array([[1,2],[3,4]])]转换为：np.array([1,2,4,9,,1,2,3,4])。注意，列表X的嵌套层数可以是任意的。

## Pandas 

1. 将A1.csv-A5.csv 读入合并，同一个股票合并为一行。注意，这些表格中都有相同的代码和名称列,可以用它们作为index。也可能有一些冗余的列和行，对数据进行清理。
2. 按"细分行业" 将资产分组 
   +  统计平均市盈率，平均价格；
   + 用总资产作权重，计算加权市盈率和加权平均价格；
   + 用流通市值作权重，计算加权市盈率和加权平均价格；
3. 按"地区" 将资产分组，重新计算2中问题
4. 将上述计算结果合并后存为csv文件。


In [107]:
import os
import sys

import numpy as np
from numpy.random import randn
from pandas import Series, DataFrame
import pandas as pd
import matplotlib.pyplot as plt


np.random.seed(12345)
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4)

## Numpy 第一题
给定一个二维数组，每行是一个向量。找出所有不同的行。
比如： 

```x = np.array([[1., 2., 3.], [4., 5., 6.],[1., 2., 3.], [4., 5., 6.]]),则
x[:2]，即x的第0,1行，array([[ 1.,  2.,  3.],[ 4.,  5.,  6.]])就是要找到行。
```

备注：请不要直接调用numpy.unique

In [108]:
import numpy as np
def find(arr):
    length=len(arr.shape)
    if length==1:
        print('The array only has one row.')
        return arr
    m=arr.shape[0]
    remark=np.zeros((m,1))
    for i in range(0,m):
        for j in range(0,m):
            if np.all(arr[i]==arr[j]):
                remark[i]+=1
    output=[]
    for i in range(0,m):
        if remark[i]==1:
            output.append(arr[i])
    return np.array(output)

In [109]:
#测试
arr1=np.array(range(0,15))
print(find(arr1),'\n')
arr2=np.array(range(0,15)).reshape((5,3))
print(find(arr2),'\n')
arr3=np.array([[1,2,3],[4,5,6],[1,2,3]])
print(find(arr3))

The array only has one row.
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[[4 5 6]]


## Numpy 第二题
a).产生正态数据数据向量 Z,长度为T， 建立一个二维数组，使其第一行为 (Z[0],Z[1],Z[2])，然后每一行都后移一位 （因此最后一行为 (Z[T-3],Z[T-2],Z[T-1] );b). 计算每列数据的样本均值，方差，各列之间的协方差。

In [110]:
import numpy as np
def solve1(T):
    arr=np.random.randn(T)
    output=np.zeros((T-2,3))
    for i in range(0,T-3):
        output[i,0]=arr[i]
        output[i,1]=arr[i+1]
        output[i,2]=arr[i+2]
    print('所求的二维数组是：\n',output,'\n')
    print('每列数据的样本均值是\n',np.mean(output,axis=0),'\n\n')
    print('每列数据的样本方差是\n',np.var(output,axis=0),'\n\n')
    print('每列数据的样本协方差是\n',np.cov(output,rowvar=False))
    return 

In [111]:
#测试
solve1(15)

所求的二维数组是：
 [[-0.2047  0.4789 -0.5194]
 [ 0.4789 -0.5194 -0.5557]
 [-0.5194 -0.5557  1.9658]
 [-0.5557  1.9658  1.3934]
 [ 1.9658  1.3934  0.0929]
 [ 1.3934  0.0929  0.2817]
 [ 0.0929  0.2817  0.769 ]
 [ 0.2817  0.769   1.2464]
 [ 0.769   1.2464  1.0072]
 [ 1.2464  1.0072 -1.2962]
 [ 1.0072 -1.2962  0.275 ]
 [-1.2962  0.275   0.2289]
 [ 0.      0.      0.    ]] 

每列数据的样本均值是
 [0.3584 0.3953 0.3761] 


每列数据的样本方差是
 [0.7626 0.7374 0.7386] 


每列数据的样本协方差是
 [[ 0.8261  0.0559 -0.2975]
 [ 0.0559  0.7988  0.0618]
 [-0.2975  0.0618  0.8001]]


## Numpy 第三题
a). 随机生成一个1000行50列二维数组，每个元素等概率取值0，1，2，并将该数组按第1列递增和第2列递减对每行排序，即先按第一列递增排序，然后在第一列每组中， 按第二列递减排序。 b). 编一个函数sortbycols(data,cols,descending)，实现行排序。给定参数 data是二维数值，cols是数或list,给出需要排序的列，descending是布尔值或布尔向量，如果是一个布尔值，则所有列都按该顺序排，如果descending是和cols等长的list，则各列按descending给定的顺序排。

+ Solution1：这里理解为对第一列或者第二列进行排序的时候，其他的元素不会动

In [112]:
#Solution1：这里理解为对第一列或者第二列进行排序的时候，其他的元素不会动
import numpy as np
arr=np.random.choice([0,1,2],size=(1000,50))
arr[:,0]=np.sort(arr[:,0])#对第一列进行递增排序
i=0
while i<=999:
    start,end=0,0
    if arr[i][0]==1:
        end=i-1
        arr[start:end,1]=np.sort(arr[start:end,1])[::-1]#对第一列是0的行的第二列进行递减排序
        start=i
    if arr[i][0]==2:
        end=i-1
        arr[start:end,1]=np.sort(arr[start:end,1])[::-1]#对第一列是1的行的第二列进行递减排序
        start=i
        arr[start:,1]=np.sort(arr[start:,1])[::-1]#对第一列是2的行的第二列进行递减排序
    i=i+1
print(arr)

[[0 2 1 ... 0 0 1]
 [0 2 2 ... 2 0 1]
 [0 2 1 ... 1 0 2]
 ...
 [2 0 1 ... 1 2 0]
 [2 0 2 ... 2 2 1]
 [2 0 0 ... 2 1 1]]


+ Solution2:理解为单一列进行排序的时候，同一行的元素相对位置不变

In [146]:
#Solution2:理解为单一列进行排序的时候，同一行的元素相对位置不变
import numpy as np
import copy

def sort1(a,col):
    """ 输入一个二维数组a，对col列进行递增排序，同一行元素相对位置不变，返回排序之后的二维数组"""
    arr=copy.deepcopy(a)[:,col]#深度拷贝，取出第col列
    if len(a.shape)==1:
        return a
    #用最简单的冒泡排序就行了,但是为了节约时间，我们可以只记住行号，最后集合到一起返回
    m=a.shape[0]
    index=np.array(range(0,m))
    i=0
    while i<m-1:
        j=0
        while j<m-1-i:
            if arr[j]>arr[j+1]:
                arr[j],arr[j+1]=arr[j+1],arr[j]
                index[j],index[j+1]=index[j+1],index[j]###核心目的是为了确定行是怎么变的
            j=j+1
        i=i+1
    output=[]
    for i in index:
        output.append(a[i])
    return np.array(output)

def sort2(a,col):
    """ 输入一个二维数组a，对col列进行递减排序，同一行元素相对位置不变，返回排序之后的二维数组"""
    arr=copy.deepcopy(a)[:,col]#深度拷贝，取出第col列
    if len(a.shape)==1:
        return a
    #用最简单的冒泡排序就行了,但是为了节约时间，我们可以只记住行号，最后集合到一起返回
    m=a.shape[0]
    index=np.array(range(0,m))
    i=0
    while i<m-1:
        j=0
        while j<m-1-i:
            if arr[j]<arr[j+1]:
                arr[j],arr[j+1]=arr[j+1],arr[j]
                index[j],index[j+1]=index[j+1],index[j]###核心目的是为了确是行是怎么变的
            j=j+1
        i=i+1
    output=[]
    for i in index:
        output.append(a[i])
    return np.array(output)

In [144]:
#test
arr=np.array([[2,3,3],[1,2,2],[3,4,4],[0,2,3]])
print(arr,'\n')
print(sort1(arr,0))

[[2 3 3]
 [1 2 2]
 [3 4 4]
 [0 2 3]] 

[[0 2 3]
 [1 2 2]
 [2 3 3]
 [3 4 4]]


In [147]:
import numpy as np
arr=np.random.choice([0,1,2],size=(1000,50))
arr=sort1(arr,0)#对第一列进行递增排序
i=0
while i<=999:
    start,end=0,0
    if arr[i][0]==1:
        end=i-1
        arr[start:end,:]=sort2(arr[start:end,:],1)#对第一列是0的行的第二列进行递减排序
        start=i
    if arr[i][0]==2:
        end=i-1
        arr[start:end,:]=sort2(arr[start:end,:],1)#对第一列是1的行的第二列进行递减排序
        start=i
        arr[start:,:]=sort2(arr[start:,:],1)#对第一列是2的行的第二列进行递减排序
    i=i+1
print(arr)

KeyboardInterrupt: 

+ 太慢了

In [119]:
arr=np.array([[9,3,4],[1,2,3],[0,0,0]])
arr

array([[9, 3, 4],
       [1, 2, 3],
       [0, 0, 0]])

In [130]:
np.argsort(arr)

array([[1, 2, 0],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [134]:
arr=np.random.randn(1000)
arr.shape
m=1000
i=0
while i<m-1:
    j=0
    while j<m-i-1:
        if arr[j]>arr[j+1]:
            arr[j],arr[j+1]=arr[j+1],arr[j]
        j=j+1
    i=i+1
print(arr)

[-2.6322e+00 -2.6011e+00 -2.5384e+00 -2.4616e+00 -2.4604e+00 -2.3185e+00
 -2.2108e+00 -2.1771e+00 -2.1703e+00 -2.0905e+00 -2.0816e+00 -2.0696e+00
 -2.0506e+00 -2.0316e+00 -2.0030e+00 -1.9650e+00 -1.9546e+00 -1.9526e+00
 -1.9425e+00 -1.9343e+00 -1.8658e+00 -1.8400e+00 -1.8292e+00 -1.8237e+00
 -1.8188e+00 -1.8125e+00 -1.7939e+00 -1.7620e+00 -1.7284e+00 -1.7180e+00
 -1.7175e+00 -1.7086e+00 -1.6722e+00 -1.6541e+00 -1.6535e+00 -1.6302e+00
 -1.6127e+00 -1.6118e+00 -1.6101e+00 -1.5878e+00 -1.5870e+00 -1.5822e+00
 -1.5727e+00 -1.5720e+00 -1.5668e+00 -1.5657e+00 -1.5332e+00 -1.5245e+00
 -1.5130e+00 -1.5094e+00 -1.5063e+00 -1.5049e+00 -1.5026e+00 -1.4989e+00
 -1.4962e+00 -1.4856e+00 -1.4800e+00 -1.4716e+00 -1.4695e+00 -1.4686e+00
 -1.4672e+00 -1.4667e+00 -1.4660e+00 -1.4576e+00 -1.4487e+00 -1.4390e+00
 -1.4373e+00 -1.4336e+00 -1.4211e+00 -1.4190e+00 -1.4168e+00 -1.4060e+00
 -1.4022e+00 -1.3992e+00 -1.3913e+00 -1.3900e+00 -1.3804e+00 -1.3802e+00
 -1.3784e+00 -1.3733e+00 -1.3638e+00 -1.3614e+00 -1