
## Numpy

1.  给定一个二维数组，每行是一个向量。找出所有不同的行。
比如： 

```x = np.array([[1., 2., 3.], [4., 5., 6.],[1., 2., 3.], [4., 5., 6.]]),则
x[:2]，即x的第0,1行，array([[ 1.,  2.,  3.],[ 4.,  5.,  6.]])就是要找到行。
```

备注：请不要直接调用numpy.unique

2.  a).产生正态数据数据向量 Z,长度为T， 建立一个二维数组，使其第一行为 (Z[0],Z[1],Z[2])，然后每一行都后移一位 （因此最后一行为 (Z[T-3],Z[T-2],Z[T-1] );b). 计算每列数据的样本均值，方差，各列之间的协方差。
 
3. a). 随机生成一个1000行50列二维数组，每个元素等概率取值0，1，2，并将该数组按第1列递增和第2列递减对每行排序，即先按第一列递增排序，然后在第一列每组中， 按第二列递减排序。 b). 编一个函数sortbycols(data,cols,descending)，实现行排序。给定参数 data是二维数值，cols是数或list,给出需要排序的列，descending是布尔值或布尔向量，如果是一个布尔值，则所有列都按该顺序排，如果descending是和cols等长的list，则各列按descending给定的顺序排。
4.  熟悉学习numpy中的现金流函数, np.pv,np.fv,np.nper,np.pmt,np.rate, 然后编制一个函数，计算给定现金流(array)，利率(array),任意时刻(t)的现金价值。

5. 有一个列表X,里面的元素可能是数，包含数的list,或者数值型np.array。请编一个函数把它转换为一维np.array数据。 比如将X=[[1,[2,[4,9]]],np.array([[1,2],[3,4]])]转换为：np.array([1,2,4,9,,1,2,3,4])。注意，列表X的嵌套层数可以是任意的。

## Pandas 

1. 将A1.csv-A5.csv 读入合并，同一个股票合并为一行。注意，这些表格中都有相同的代码和名称列,可以用它们作为index。也可能有一些冗余的列和行，对数据进行清理。
2. 按"细分行业" 将资产分组 
   +  统计平均市盈率，平均价格；
   + 用总资产作权重，计算加权市盈率和加权平均价格；
   + 用流通市值作权重，计算加权市盈率和加权平均价格；
3. 按"地区" 将资产分组，重新计算2中问题
4. 将上述计算结果合并后存为csv文件。


In [1]:
import os
import sys

import numpy as np
from numpy.random import randn
from pandas import Series, DataFrame
import pandas as pd
import matplotlib.pyplot as plt


np.random.seed(12345)
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4)

## Numpy 第一题
给定一个二维数组，每行是一个向量。找出所有不同的行。
比如： 

```x = np.array([[1., 2., 3.], [4., 5., 6.],[1., 2., 3.], [4., 5., 6.]]),则
x[:2]，即x的第0,1行，array([[ 1.,  2.,  3.],[ 4.,  5.,  6.]])就是要找到行。
```

备注：请不要直接调用numpy.unique

In [2]:
import numpy as np
def find(arr):
    length=len(arr.shape)
    if length==1:
        print('The array only has one row.')
        return arr
    m=arr.shape[0]
    remark=np.zeros((m,1))
    for i in range(0,m):
        for j in range(0,m):
            if np.all(arr[i]==arr[j]):
                remark[i]+=1
    output=[]
    for i in range(0,m):
        if remark[i]==1:
            output.append(arr[i])
    return np.array(output)

In [3]:
#测试
arr1=np.array(range(0,15))
print(find(arr1),'\n')
arr2=np.array(range(0,15)).reshape((5,3))
print(find(arr2),'\n')
arr3=np.array([[1,2,3],[4,5,6],[1,2,3]])
print(find(arr3))

The array only has one row.
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[[4 5 6]]


## Numpy 第二题
a).产生正态数据数据向量 Z,长度为T， 建立一个二维数组，使其第一行为 (Z[0],Z[1],Z[2])，然后每一行都后移一位 （因此最后一行为 (Z[T-3],Z[T-2],Z[T-1] );b). 计算每列数据的样本均值，方差，各列之间的协方差。

In [4]:
import numpy as np
def solve1(T):
    arr=np.random.randn(T)
    output=np.zeros((T-2,3))
    for i in range(0,T-3):
        output[i,0]=arr[i]
        output[i,1]=arr[i+1]
        output[i,2]=arr[i+2]
    print('所求的二维数组是：\n',output,'\n')
    print('每列数据的样本均值是\n',np.mean(output,axis=0),'\n\n')
    print('每列数据的样本方差是\n',np.var(output,axis=0),'\n\n')
    print('每列数据的样本协方差是\n',np.cov(output,rowvar=False))
    return 

In [5]:
#测试
solve1(15)

所求的二维数组是：
 [[-0.2047  0.4789 -0.5194]
 [ 0.4789 -0.5194 -0.5557]
 [-0.5194 -0.5557  1.9658]
 [-0.5557  1.9658  1.3934]
 [ 1.9658  1.3934  0.0929]
 [ 1.3934  0.0929  0.2817]
 [ 0.0929  0.2817  0.769 ]
 [ 0.2817  0.769   1.2464]
 [ 0.769   1.2464  1.0072]
 [ 1.2464  1.0072 -1.2962]
 [ 1.0072 -1.2962  0.275 ]
 [-1.2962  0.275   0.2289]
 [ 0.      0.      0.    ]] 

每列数据的样本均值是
 [0.3584 0.3953 0.3761] 


每列数据的样本方差是
 [0.7626 0.7374 0.7386] 


每列数据的样本协方差是
 [[ 0.8261  0.0559 -0.2975]
 [ 0.0559  0.7988  0.0618]
 [-0.2975  0.0618  0.8001]]


## Numpy 第三题
a). 随机生成一个1000行50列二维数组，每个元素等概率取值0，1，2，并将该数组按第1列递增和第2列递减对每行排序，即先按第一列递增排序，然后在第一列每组中， 按第二列递减排序。 b). 编一个函数sortbycols(data,cols,descending)，实现行排序。给定参数 data是二维数值，cols是数或list,给出需要排序的列，descending是布尔值或布尔向量，如果是一个布尔值，则所有列都按该顺序排，如果descending是和cols等长的list，则各列按descending给定的顺序排。

a). 随机生成一个1000行50列二维数组，每个元素等概率取值0，1，2，并将该数组按第1列递增和第2列递减对每行排序，即先按第一列递增排序，然后在第一列每组中， 按第二列递减排序。

+ Solution1：这里理解为对第一列或者第二列进行排序的时候，其他的元素不会动

In [6]:
#Solution1：这里理解为对第一列或者第二列进行排序的时候，其他的元素不会动
import numpy as np
arr=np.random.choice([0,1,2],size=(1000,50))
arr[:,0]=np.sort(arr[:,0])#对第一列进行递增排序
i=0
while i<=999:
    start,end=0,0
    if arr[i][0]==1:
        end=i-1
        arr[start:end,1]=np.sort(arr[start:end,1])[::-1]#对第一列是0的行的第二列进行递减排序
        start=i
    if arr[i][0]==2:
        end=i-1
        arr[start:end,1]=np.sort(arr[start:end,1])[::-1]#对第一列是1的行的第二列进行递减排序
        start=i
        arr[start:,1]=np.sort(arr[start:,1])[::-1]#对第一列是2的行的第二列进行递减排序
    i=i+1
print(arr)

[[0 2 1 ... 0 0 1]
 [0 2 2 ... 2 0 1]
 [0 2 1 ... 1 0 2]
 ...
 [2 0 1 ... 1 2 0]
 [2 0 2 ... 2 2 1]
 [2 0 0 ... 2 1 1]]


+ Solution2:理解为单一列进行排序的时候，同一行的元素相对位置不变

In [63]:
#Solution2:理解为单一列进行排序的时候，同一行的元素相对位置不变
import numpy as np
import copy

def sort1(a,col):
    """ 输入一个二维数组a，对col列进行递增排序，同一行元素相对位置不变，返回排序之后的二维数组"""
    arr=copy.deepcopy(a)[:,col]#深度拷贝，取出第col列
    if len(a.shape)==1:
        return a
    #用最简单的冒泡排序就行了,但是为了节约时间，我们可以只记住行号，最后集合到一起返回
    m=a.shape[0]
    index=np.array(range(0,m))
    i=0
    while i<m-1:
        j=0
        while j<m-1-i:
            if arr[j]>arr[j+1]:
                arr[j],arr[j+1]=arr[j+1],arr[j]
                index[j],index[j+1]=index[j+1],index[j]###核心目的是为了确定行是怎么变的
            j=j+1
        i=i+1
    output=[]
    for i in index:
        output.append(a[i])
    return np.array(output)

def sort2(a,col):
    """ 输入一个二维数组a，对col列进行递减排序，同一行元素相对位置不变，返回排序之后的二维数组"""
    arr=copy.deepcopy(a)[:,col]#深度拷贝，取出第col列
    if len(a.shape)==1:
        return a
    #用最简单的冒泡排序就行了,但是为了节约时间，我们可以只记住行号，最后集合到一起返回
    m=a.shape[0]
    index=np.array(range(0,m))
    i=0
    while i<m-1:
        j=0
        while j<m-1-i:
            if arr[j]<arr[j+1]:
                arr[j],arr[j+1]=arr[j+1],arr[j]
                index[j],index[j+1]=index[j+1],index[j]###核心目的是为了确是行是怎么变的
            j=j+1
        i=i+1
    output=[]
    for i in index:
        output.append(a[i])
    return np.array(output)

In [ ]:
import numpy as np
arr=np.random.choice([0,1,2],size=(1000,50))
arr=sort1(arr,0)#对第一列进行递增排序
i=0
while i<=999:
    start,end=0,0
    if arr[i][0]==1:
        end=i-1
        arr[start:end,:]=sort2(arr[start:end,:],1)#对第一列是0的行的第二列进行递减排序
        start=i
    if arr[i][0]==2:
        end=i-1
        arr[start:end,:]=sort2(arr[start:end,:],1)#对第一列是1的行的第二列进行递减排序
        start=i
        arr[start:,:]=sort2(arr[start:,:],1)#对第一列是2的行的第二列进行递减排序
    i=i+1
print(arr)

b). 编一个函数sortbycols(data,cols,descending)，实现行排序。给定参数 data是二维数值，cols是数或list,给出需要排序的列，descending是布尔值或布尔向量，如果是一个布尔值，则所有列都按该顺序排，如果descending是和cols等长的list，则各列按descending给定的顺序排。

In [7]:
import numpy as np
def sortbycols(data,cols,descending):
    """ data是一个二维数组，cols是数或者list，给出的是需要排序的列，descending是布尔值或布尔向量，如果是一个布尔值，则所有列都按照该顺序排序，如果descending是和cols等长的list，则各列按descending给定的顺序排 """
    if isinstance(descending,bool):#是bool型
        if isinstance(cols,int):#只是一列
            if descending:
                data[:,cols]=np.sort(data[:,cols])[::-1]
            else:
                data[:,cols]=np.sort(data[:,cols])
            return data
        else:#有很多列
            for i in cols:
                if descending:
                    data[:,i]=np.sort(data[:,i])[::-1]
                else:
                    data[:,i]=np.sort(data[:,i])
            return data
    else:#是bool向量
        for i,j in zip(cols,descending):
            if j:
                data[:,i]=np.sort(data[:,i])[::-1]
            else:
                data[:,i]=np.sort(data[:,i])
        return data

In [8]:
#test
a=np.array([[1,2,3],[0,-2,8],[9,9,9],[-5,0,6]])
print(a,'\n')
print(sortbycols(a,[0,1],[True,False]))

[[ 1  2  3]
 [ 0 -2  8]
 [ 9  9  9]
 [-5  0  6]] 

[[ 9 -2  3]
 [ 1  0  8]
 [ 0  2  9]
 [-5  9  6]]


## Numpy 第四题
熟悉学习numpy中的现金流函数, np.pv,np.fv,np.nper,np.pmt,np.rate, 然后编制一个函数，计算给定现金流(array)，利率(array),任意时刻(t)的现金价值。

需要下载 numpy_financial 包
> pip install numpy_financial

In [9]:
import numpy_financial as npf

In [10]:
?npf.pv
#present value
#npf.pv(rate, nper, pmt, fv=0, when='end')

Signature: npf.pv(rate, nper, pmt, fv=0, when='end')
Docstring:
Compute the present value.

Given:
 * a future value, `fv`
 * an interest `rate` compounded once per period, of which
   there are
 * `nper` total
 * a (fixed) payment, `pmt`, paid either
 * at the beginning (`when` = {'begin', 1}) or the end
   (`when` = {'end', 0}) of each period

Return:
   the value now

Parameters
----------
rate : array_like
    Rate of interest (per period)
nper : array_like
    Number of compounding periods
pmt : array_like
    Payment
fv : array_like, optional
    Future value
when : {{'begin', 1}, {'end', 0}}, {string, int}, optional
    When payments are due ('begin' (1) or 'end' (0))

Returns
-------
out : ndarray, float
    Present value of a series of payments or investments.

Notes
-----
The present value is computed by solving the equation::

 fv +
 pv*(1 + rate)**nper +
 pmt*(1 + rate*when)/rate*((1 + rate)**nper - 1) = 0

or, when ``rate = 0``::

 fv + pv + pmt * nper = 0

for `pv`, which

In [11]:
?npf.fv
#future value
#npf.fv(rate, nper, pmt, pv, when='end')

Signature: npf.fv(rate, nper, pmt, pv, when='end')
Docstring:
Compute the future value.

Given:
 * a present value, `pv`
 * an interest `rate` compounded once per period, of which
   there are
 * `nper` total
 * a (fixed) payment, `pmt`, paid either
 * at the beginning (`when` = {'begin', 1}) or the end
   (`when` = {'end', 0}) of each period

Return:
   the value at the end of the `nper` periods

Parameters
----------
rate : scalar or array_like of shape(M, )
    Rate of interest as decimal (not per cent) per period
nper : scalar or array_like of shape(M, )
    Number of compounding periods
pmt : scalar or array_like of shape(M, )
    Payment
pv : scalar or array_like of shape(M, )
    Present value
when : {{'begin', 1}, {'end', 0}}, {string, int}, optional
    When payments are due ('begin' (1) or 'end' (0)).
    Defaults to {'end', 0}.

Returns
-------
out : ndarray
    Future values.  If all input is scalar, returns a scalar float.  If
    any input is array_like, returns future va

In [12]:
?npf.nper
#periodic payments
#npf.nper(rate, pmt, pv, fv=0, when='end')

Signature: npf.nper(rate, pmt, pv, fv=0, when='end')
Docstring:
Compute the number of periodic payments.

:class:`decimal.Decimal` type is not supported.

Parameters
----------
rate : array_like
    Rate of interest (per period)
pmt : array_like
    Payment
pv : array_like
    Present value
fv : array_like, optional
    Future value
when : {{'begin', 1}, {'end', 0}}, {string, int}, optional
    When payments are due ('begin' (1) or 'end' (0))

Notes
-----
The number of periods ``nper`` is computed by solving the equation::

 fv + pv*(1+rate)**nper + pmt*(1+rate*when)/rate*((1+rate)**nper-1) = 0

but if ``rate = 0`` then::

 fv + pv + pmt*nper = 0

Examples
--------
>>> import numpy as np
>>> import numpy_financial as npf

If you only had $150/month to pay towards the loan, how long would it take
to pay-off a loan of $8,000 at 7% annual interest?

>>> print(np.round(npf.nper(0.07/12, -150, 8000), 5))
64.07335

So, over 64 months would be required to pay off the loan.

The same analysis 

In [13]:
?npf.pmt
#payment
#npf.pmt(rate, nper, pv, fv=0, when='end')

Signature: npf.pmt(rate, nper, pv, fv=0, when='end')
Docstring:
Compute the payment against loan principal plus interest.

Given:
 * a present value, `pv` (e.g., an amount borrowed)
 * a future value, `fv` (e.g., 0)
 * an interest `rate` compounded once per period, of which
   there are
 * `nper` total
 * and (optional) specification of whether payment is made
   at the beginning (`when` = {'begin', 1}) or the end
   (`when` = {'end', 0}) of each period

Return:
   the (fixed) periodic payment.

Parameters
----------
rate : array_like
    Rate of interest (per period)
nper : array_like
    Number of compounding periods
pv : array_like
    Present value
fv : array_like,  optional
    Future value (default = 0)
when : {{'begin', 1}, {'end', 0}}, {string, int}
    When payments are due ('begin' (1) or 'end' (0))

Returns
-------
out : ndarray
    Payment against loan plus interest.  If all input is scalar, returns a
    scalar float.  If any input is array_like, returns payment for each
 

In [14]:
?npf.rate
#Compute the rate of interest per period.
#npf.rate(nper, pmt, pv, fv, when='end', guess=None, tol=None, maxiter=100)

Signature: npf.rate(nper, pmt, pv, fv, when='end', guess=None, tol=None, maxiter=100)
Docstring:
Compute the rate of interest per period.

Parameters
----------
nper : array_like
    Number of compounding periods
pmt : array_like
    Payment
pv : array_like
    Present value
fv : array_like
    Future value
when : {{'begin', 1}, {'end', 0}}, {string, int}, optional
    When payments are due ('begin' (1) or 'end' (0))
guess : Number, optional
    Starting guess for solving the rate of interest, default 0.1
tol : Number, optional
    Required tolerance for the solution, default 1e-6
maxiter : int, optional
    Maximum iterations in finding the solution

Notes
-----
The rate of interest is computed by iteratively solving the
(non-linear) equation::

 fv + pv*(1+rate)**nper + pmt*(1+rate*when)/rate * ((1+rate)**nper - 1) = 0

for ``rate``.

References
----------
Wheeler, D. A., E. Rathke, and R. Weir (Eds.) (2009, May). Open Document
Format for Office Applications (OpenDocument)v1.2, Part 

In [15]:
def solution(a,b,t):
    """
    计算给定现金流(array)，利率(array),任意时刻(t)的现金价值
    现金流:a, 利率:b, 时刻t
    """
    

## Numpy 第五题
有一个列表X,里面的元素可能是数，包含数的list,或者数值型np.array。请编一个函数把它转换为一维np.array数据。 比如将X=[[1,[2,[4,9]]],np.array([[1,2],[3,4]])]转换为：np.array([1,2,4,9,,1,2,3,4])。注意，列表X的嵌套层数可以是任意的

In [16]:
def solution(x):
    """
    有一个列表X,里面的元素可能是数，包含数的list,或者数值型np.array。请编一个函数把它转换为一维np.array数据。 比如将X=[[1,[2,[4,9]]],np.array([[1,2],[3,4]])]转换为：np.array([1,2,4,9,,1,2,3,4])。注意，列表X的嵌套层数可以是任意的
    """
    #使用递归或者循环，感觉有点像tree结构
    if isinstance(x,np.ndarray):
        return x.flatten()#使用flatten进行展平
    elif isinstance(x,list):
        output=[]
        for i in x:
            output.extend(solution(i))
        return np.array(output)
    else:#是数字
        return np.array([x])

In [17]:
#test
X=[[1,[2,[4,9]]],np.array([[1,2],[3,4]])]
print(X,'\n')
solution(X)

[[1, [2, [4, 9]]], array([[1, 2],
       [3, 4]])] 



array([1, 2, 4, 9, 1, 2, 3, 4])

## Pandas 第一题
将A1.csv-A5.csv 读入合并，同一个股票合并为一行。注意，这些表格中都有**相同的代码和名称列**,可以用它们作为index。也可能有一些冗余的列和行，对数据进行清理。

In [100]:
import os
import sys

import numpy as np
from numpy.random import randn
from pandas import Series, DataFrame
import pandas as pd

In [101]:
%pwd

'c:\\Users\\16017\\Desktop\\Dropbox\\金融数据分析导引\\Guide_to_financial_data_analysis\\hw\\hw2'

In [149]:
#读入文件
df1=pd.read_csv('A1.csv',encoding='ANSI')
df2=pd.read_csv('A2.csv',encoding='ANSI')
df3=pd.read_csv('A3.csv',encoding='ANSI')
df4=pd.read_csv('A4.csv',encoding='ANSI')
df5=pd.read_csv('A5.csv',encoding='ANSI')

In [150]:
#清理数据
df1.drop(index=[2780],axis=0,inplace=True)
df2.drop(index=[2780],axis=0,inplace=True)
df2.drop(labels='未匹配量',axis=1,inplace=True)
df3.drop(index=[2780],axis=0,inplace=True)
df4.drop(index=[2780],axis=0,inplace=True)
df5.drop(index=[2780],axis=0,inplace=True)

In [151]:
#合并
output=pd.merge(df1,df2,on=['代码','名称'])
output=pd.merge(output,df3,on=['代码','名称'])
output=pd.merge(output,df4,on=['代码','名称'])
output=pd.merge(output,df5,on=['代码','名称'])

## Pandas 第二题
按"细分行业" 将资产分组 
+  统计平均市盈率，平均价格；
+ 用总资产作权重，计算加权市盈率和加权平均价格；
+ 用流通市值作权重，计算加权市盈率和加权平均价格；

In [152]:
output

代码     名称  收入同比%%  利润同比%% 营业利润率%%     市销率    市净率     市现率   市盈(动)  \
0     000001   平安银行   34.09   15.02   32.78    3.64   1.12    0.93    7.31   
1     000002  万  科Ａ   22.72    0.77   17.35    3.13   1.80  -23.08   16.21   
2     000004   国农科技  117.08  125.75   10.98   36.85  26.93 -337.10  905.17   
3     000005   世纪星源   52.10    8.05  -64.57  148.17   8.32  155.10    --     
4     000006   深振业Ａ  311.53  425.18   17.93    6.29   3.01  -20.19   24.66   
...      ...    ...     ...     ...     ...     ...    ...     ...     ...   
2775  603989   艾华集团    0.00    0.00   18.72   11.11   3.71   75.26   37.25   
2776  603993   洛阳钼业  -38.77  -53.92   19.07   30.36   4.43   55.15    74.4   
2777  603997   继峰股份    0.00    0.00   20.07   12.11   4.87   53.97   34.88   
2778  603998   方盛制药   14.86   12.48   26.95   19.08   5.18  128.87    45.8   
2779  600656  *ST博元    0.00 -874.28    --      0.00   0.00    0.00    --     

             总金额  ...     每股收益   每股净资 调整后净资  每股公积  每股未分配     权益比  \
0     3273803264  ...   0.840㈡  10.54  0.00  4.15   3.72    5.87   
1     3218100480  ...   0.439㈡   7.90  0.00  0.75   3.74   16.25   
2      175093968  ...   0.014㈡   0.97  0.00  0.01  -0.17   23.37   
3              0  ...  -0.025㈡   0.71  0.00  0.30  -0.59   48.19   
4      504695104  ...   0.191㈡   3.14  0.00  0.36   1.00   35.97   
...          ...  ...      ...    ...   ...   ...    ...     ...   
2775    91359128  ...   0.560㈡   8.95  0.00  5.13   2.49   87.41   
2776  1251790080  ...   0.090㈡   2.76  2.76  1.77   0.49   43.76   
2777    48540316  ...   0.220㈡   2.96  0.00  0.97   0.87   89.37   
2778   278240704  ...   0.336㈡   5.94  0.00  2.80   1.92   86.59   
2779        --    ...  -0.072㈡  -2.08  0.00  1.03  -4.14 -331.22   

                净益率%% 销售毛利率%%     今开  净利润率%%  
0               7.68㈡    --    11.18   24.87  
1               5.55㈡   30.45  13.77    9.64  
2               1.49㈡   35.95     27    2.04  
3              -3.59㈡   29.93   --    -63.91  
4               6.09㈡   33.74   8.85   12.76  
...               ...     ...    ...     ...  
2775            4.98㈡   33.27  32.87   14.91  
2776            3.26㈡   41.44  11.32    20.4  
2777            6.98㈡   37.52  14.12   17.35  
2778            5.66㈡    55.3     32   20.83  
2779             --      --     --      --    

[2780 rows x 71 columns]

In [ ]:
grouped=output.groupby('细分行业')
list(grouped['市盈(动)'])

In [176]:
output

代码     名称  收入同比%%  利润同比%% 营业利润率%%     市销率    市净率     市现率   市盈(动)  \
0     000001   平安银行   34.09   15.02   32.78    3.64   1.12    0.93    7.31   
1     000002  万  科Ａ   22.72    0.77   17.35    3.13   1.80  -23.08   16.21   
2     000004   国农科技  117.08  125.75   10.98   36.85  26.93 -337.10  905.17   
3     000005   世纪星源   52.10    8.05  -64.57  148.17   8.32  155.10    --     
4     000006   深振业Ａ  311.53  425.18   17.93    6.29   3.01  -20.19   24.66   
...      ...    ...     ...     ...     ...     ...    ...     ...     ...   
2775  603989   艾华集团    0.00    0.00   18.72   11.11   3.71   75.26   37.25   
2776  603993   洛阳钼业  -38.77  -53.92   19.07   30.36   4.43   55.15    74.4   
2777  603997   继峰股份    0.00    0.00   20.07   12.11   4.87   53.97   34.88   
2778  603998   方盛制药   14.86   12.48   26.95   19.08   5.18  128.87    45.8   
2779  600656  *ST博元    0.00 -874.28    --      0.00   0.00    0.00    --     

             总金额  ...     每股收益   每股净资 调整后净资  每股公积  每股未分配     权益比  \
0     3273803264  ...   0.840㈡  10.54  0.00  4.15   3.72    5.87   
1     3218100480  ...   0.439㈡   7.90  0.00  0.75   3.74   16.25   
2      175093968  ...   0.014㈡   0.97  0.00  0.01  -0.17   23.37   
3              0  ...  -0.025㈡   0.71  0.00  0.30  -0.59   48.19   
4      504695104  ...   0.191㈡   3.14  0.00  0.36   1.00   35.97   
...          ...  ...      ...    ...   ...   ...    ...     ...   
2775    91359128  ...   0.560㈡   8.95  0.00  5.13   2.49   87.41   
2776  1251790080  ...   0.090㈡   2.76  2.76  1.77   0.49   43.76   
2777    48540316  ...   0.220㈡   2.96  0.00  0.97   0.87   89.37   
2778   278240704  ...   0.336㈡   5.94  0.00  2.80   1.92   86.59   
2779        --    ...  -0.072㈡  -2.08  0.00  1.03  -4.14 -331.22   

                净益率%% 销售毛利率%%     今开  净利润率%%  
0               7.68㈡    --    11.18   24.87  
1               5.55㈡   30.45  13.77    9.64  
2               1.49㈡   35.95     27    2.04  
3              -3.59㈡   29.93   --    -63.91  
4               6.09㈡   33.74   8.85   12.76  
...               ...     ...    ...     ...  
2775            4.98㈡   33.27  32.87   14.91  
2776            3.26㈡   41.44  11.32    20.4  
2777            6.98㈡   37.52  14.12   17.35  
2778            5.66㈡    55.3     32   20.83  
2779             --      --     --      --    

[2780 rows x 71 columns]

In [172]:
means=output['市盈(动)'].groupby(output['细分行业']).mean()
#报错：因为有'--'

TypeError: Could not convert 13.9270.39176.45175.9336.7231.3177.137.73--  211.14--  25.3880.9478.6126.85303.571431.682.577.3253.39122.91175.79107.73122.3633.12219.33225.3942.8566.2942.51--  84.4735.29--  64.79122.29231.95105.67697.2252.3658.83174.3251.21137.3652.34--  34.5168.9763.67607.11195.9933.9650.7973.2436.484.7373.6284.1262.4243.4271.4135.5767.4355.2236.352743.9129.4238.8362.37295.63--  44.8985.3334.4754.4384.7998.36 to numeric