
## Numpy

1.  给定一个二维数组，每行是一个向量。找出所有不同的行。
比如： 

```x = np.array([[1., 2., 3.], [4., 5., 6.],[1., 2., 3.], [4., 5., 6.]]),则
x[:2]，即x的第0,1行，array([[ 1.,  2.,  3.],[ 4.,  5.,  6.]])就是要找到行。
```

备注：请不要直接调用numpy.unique

2.  a).产生正态数据数据向量 Z,长度为T， 建立一个二维数组，使其第一行为 (Z[0],Z[1],Z[2])，然后每一行都后移一位 （因此最后一行为 (Z[T-3],Z[T-2],Z[T-1] );b). 计算每列数据的样本均值，方差，各列之间的协方差。
 
3. a). 随机生成一个1000行50列二维数组，每个元素等概率取值0，1，2，并将该数组按第1列递增和第2列递减对每行排序，即先按第一列递增排序，然后在第一列每组中， 按第二列递减排序。 b). 编一个函数sortbycols(data,cols,descending)，实现行排序。给定参数 data是二维数值，cols是数或list,给出需要排序的列，descending是布尔值或布尔向量，如果是一个布尔值，则所有列都按该顺序排，如果descending是和cols等长的list，则各列按descending给定的顺序排。
4.  熟悉学习numpy中的现金流函数, np.pv,np.fv,np.nper,np.pmt,np.rate, 然后编制一个函数，计算给定现金流(array)，利率(array),任意时刻(t)的现金价值。

5. 有一个列表X,里面的元素可能是数，包含数的list,或者数值型np.array。请编一个函数把它转换为一维np.array数据。 比如将X=[[1,[2,[4,9]]],np.array([[1,2],[3,4]])]转换为：np.array([1,2,4,9,,1,2,3,4])。注意，列表X的嵌套层数可以是任意的。

## Pandas 

1. 将A1.csv-A5.csv 读入合并，同一个股票合并为一行。注意，这些表格中都有相同的代码和名称列,可以用它们作为index。也可能有一些冗余的列和行，对数据进行清理。
2. 按"细分行业" 将资产分组 
   + 统计平均市盈率，平均价格；
   + 用总资产作权重，计算加权市盈率和加权平均价格；
   + 用流通市值作权重，计算加权市盈率和加权平均价格；
3. 按"地区" 将资产分组，重新计算2中问题
4. 将上述计算结果合并后存为csv文件。


In [1]:
import os
import sys

import numpy as np
from numpy.random import randn
from pandas import Series, DataFrame
import pandas as pd
import matplotlib.pyplot as plt


np.random.seed(12345)
plt.rc('figure', figsize=(10, 6))
np.set_printoptions(precision=4)

## Numpy 第一题
给定一个二维数组，每行是一个向量。找出所有不同的行。
比如： 

```x = np.array([[1., 2., 3.], [4., 5., 6.],[1., 2., 3.], [4., 5., 6.]]),则
x[:2]，即x的第0,1行，array([[ 1.,  2.,  3.],[ 4.,  5.,  6.]])就是要找到行。
```

备注：请不要直接调用numpy.unique

In [2]:
import numpy as np
def find(arr):
    length=len(arr.shape)
    if length==1:
        print('The array only has one row.')
        return arr
    m=arr.shape[0]
    remark=np.zeros((m,1))
    for i in range(0,m):
        for j in range(0,m):
            if np.all(arr[i]==arr[j]):
                remark[i]+=1
    output=[]
    for i in range(0,m):
        if remark[i]==1:
            output.append(arr[i])
    return np.array(output)

In [3]:
#测试
arr1=np.array(range(0,15))
print(find(arr1),'\n')
arr2=np.array(range(0,15)).reshape((5,3))
print(find(arr2),'\n')
arr3=np.array([[1,2,3],[4,5,6],[1,2,3]])
print(find(arr3))

The array only has one row.
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[[4 5 6]]


## Numpy 第二题
a).产生正态数据数据向量 Z,长度为T， 建立一个二维数组，使其第一行为 (Z[0],Z[1],Z[2])，然后每一行都后移一位 （因此最后一行为 (Z[T-3],Z[T-2],Z[T-1] );b). 计算每列数据的样本均值，方差，各列之间的协方差。

In [4]:
import numpy as np
def solve1(T):
    arr=np.random.randn(T)
    output=np.zeros((T-2,3))
    for i in range(0,T-3):
        output[i,0]=arr[i]
        output[i,1]=arr[i+1]
        output[i,2]=arr[i+2]
    print('所求的二维数组是：\n',output,'\n')
    print('每列数据的样本均值是\n',np.mean(output,axis=0),'\n\n')
    print('每列数据的样本方差是\n',np.var(output,axis=0),'\n\n')
    print('每列数据的样本协方差是\n',np.cov(output,rowvar=False))
    return 

In [5]:
#测试
solve1(15)

所求的二维数组是：
 [[-0.2047  0.4789 -0.5194]
 [ 0.4789 -0.5194 -0.5557]
 [-0.5194 -0.5557  1.9658]
 [-0.5557  1.9658  1.3934]
 [ 1.9658  1.3934  0.0929]
 [ 1.3934  0.0929  0.2817]
 [ 0.0929  0.2817  0.769 ]
 [ 0.2817  0.769   1.2464]
 [ 0.769   1.2464  1.0072]
 [ 1.2464  1.0072 -1.2962]
 [ 1.0072 -1.2962  0.275 ]
 [-1.2962  0.275   0.2289]
 [ 0.      0.      0.    ]] 

每列数据的样本均值是
 [0.3584 0.3953 0.3761] 


每列数据的样本方差是
 [0.7626 0.7374 0.7386] 


每列数据的样本协方差是
 [[ 0.8261  0.0559 -0.2975]
 [ 0.0559  0.7988  0.0618]
 [-0.2975  0.0618  0.8001]]


## Numpy 第三题
a). 随机生成一个1000行50列二维数组，每个元素等概率取值0，1，2，并将该数组按第1列递增和第2列递减对每行排序，即先按第一列递增排序，然后在第一列每组中， 按第二列递减排序。 b). 编一个函数sortbycols(data,cols,descending)，实现行排序。给定参数 data是二维数值，cols是数或list,给出需要排序的列，descending是布尔值或布尔向量，如果是一个布尔值，则所有列都按该顺序排，如果descending是和cols等长的list，则各列按descending给定的顺序排。

a). 随机生成一个1000行50列二维数组，每个元素等概率取值0，1，2，并将该数组按第1列递增和第2列递减对每行排序，即先按第一列递增排序，然后在第一列每组中， 按第二列递减排序。

+ Solution1：这里理解为对第一列或者第二列进行排序的时候，其他的元素不会动

In [6]:
#Solution1：这里理解为对第一列或者第二列进行排序的时候，其他的元素不会动
import numpy as np
arr=np.random.choice([0,1,2],size=(1000,50))
arr[:,0]=np.sort(arr[:,0])#对第一列进行递增排序
i=0
while i<=999:
    start,end=0,0
    if arr[i][0]==1:
        end=i-1
        arr[start:end,1]=np.sort(arr[start:end,1])[::-1]#对第一列是0的行的第二列进行递减排序
        start=i
    if arr[i][0]==2:
        end=i-1
        arr[start:end,1]=np.sort(arr[start:end,1])[::-1]#对第一列是1的行的第二列进行递减排序
        start=i
        arr[start:,1]=np.sort(arr[start:,1])[::-1]#对第一列是2的行的第二列进行递减排序
    i=i+1
print(arr)

[[0 2 1 ... 0 0 1]
 [0 2 2 ... 2 0 1]
 [0 2 1 ... 1 0 2]
 ...
 [2 0 1 ... 1 2 0]
 [2 0 2 ... 2 2 1]
 [2 0 0 ... 2 1 1]]


+ Solution2:理解为单一列进行排序的时候，同一行的元素相对位置不变

In [63]:
#Solution2:理解为单一列进行排序的时候，同一行的元素相对位置不变
import numpy as np
import copy

def sort1(a,col):
    """ 输入一个二维数组a，对col列进行递增排序，同一行元素相对位置不变，返回排序之后的二维数组"""
    arr=copy.deepcopy(a)[:,col]#深度拷贝，取出第col列
    if len(a.shape)==1:
        return a
    #用最简单的冒泡排序就行了,但是为了节约时间，我们可以只记住行号，最后集合到一起返回
    m=a.shape[0]
    index=np.array(range(0,m))
    i=0
    while i<m-1:
        j=0
        while j<m-1-i:
            if arr[j]>arr[j+1]:
                arr[j],arr[j+1]=arr[j+1],arr[j]
                index[j],index[j+1]=index[j+1],index[j]###核心目的是为了确定行是怎么变的
            j=j+1
        i=i+1
    output=[]
    for i in index:
        output.append(a[i])
    return np.array(output)

def sort2(a,col):
    """ 输入一个二维数组a，对col列进行递减排序，同一行元素相对位置不变，返回排序之后的二维数组"""
    arr=copy.deepcopy(a)[:,col]#深度拷贝，取出第col列
    if len(a.shape)==1:
        return a
    #用最简单的冒泡排序就行了,但是为了节约时间，我们可以只记住行号，最后集合到一起返回
    m=a.shape[0]
    index=np.array(range(0,m))
    i=0
    while i<m-1:
        j=0
        while j<m-1-i:
            if arr[j]<arr[j+1]:
                arr[j],arr[j+1]=arr[j+1],arr[j]
                index[j],index[j+1]=index[j+1],index[j]###核心目的是为了确是行是怎么变的
            j=j+1
        i=i+1
    output=[]
    for i in index:
        output.append(a[i])
    return np.array(output)

In [ ]:
import numpy as np
arr=np.random.choice([0,1,2],size=(1000,50))
arr=sort1(arr,0)#对第一列进行递增排序
i=0
while i<=999:
    start,end=0,0
    if arr[i][0]==1:
        end=i-1
        arr[start:end,:]=sort2(arr[start:end,:],1)#对第一列是0的行的第二列进行递减排序
        start=i
    if arr[i][0]==2:
        end=i-1
        arr[start:end,:]=sort2(arr[start:end,:],1)#对第一列是1的行的第二列进行递减排序
        start=i
        arr[start:,:]=sort2(arr[start:,:],1)#对第一列是2的行的第二列进行递减排序
    i=i+1
print(arr)

b). 编一个函数sortbycols(data,cols,descending)，实现行排序。给定参数 data是二维数值，cols是数或list,给出需要排序的列，descending是布尔值或布尔向量，如果是一个布尔值，则所有列都按该顺序排，如果descending是和cols等长的list，则各列按descending给定的顺序排。

In [8]:
import numpy as np
def sortbycols(data,cols,descending):
    """ data是一个二维数组，cols是数或者list，给出的是需要排序的列，descending是布尔值或布尔向量，如果是一个布尔值，则所有列都按照该顺序排序，如果descending是和cols等长的list，则各列按descending给定的顺序排 """
    if isinstance(descending,bool):#是bool型
        if isinstance(cols,int):#只是一列
            if descending:
                data[:,cols]=np.sort(data[:,cols])[::-1]
            else:
                data[:,cols]=np.sort(data[:,cols])
            return data
        else:#有很多列
            for i in cols:
                if descending:
                    data[:,i]=np.sort(data[:,i])[::-1]
                else:
                    data[:,i]=np.sort(data[:,i])
            return data
    else:#是bool向量
        for i,j in zip(cols,descending):
            if j:
                data[:,i]=np.sort(data[:,i])[::-1]
            else:
                data[:,i]=np.sort(data[:,i])
        return data

In [9]:
#test
a=np.array([[1,2,3],[0,-2,8],[9,9,9],[-5,0,6]])
print(a,'\n')
print(sortbycols(a,[0,1],[True,False]))

[[ 1  2  3]
 [ 0 -2  8]
 [ 9  9  9]
 [-5  0  6]] 

[[ 9 -2  3]
 [ 1  0  8]
 [ 0  2  9]
 [-5  9  6]]


## Numpy 第四题
熟悉学习numpy中的现金流函数, np.pv,np.fv,np.nper,np.pmt,np.rate, 然后编制一个函数，计算给定现金流(array)，利率(array),任意时刻(t)的现金价值。

需要下载 numpy_financial 包
> pip install numpy_financial

In [10]:
import numpy_financial as npf

In [16]:
def solution(a,b,t):
    """
    计算给定现金流(array)，利率(array),任意时刻(t)的现金价值
    现金流:a, 利率:b, 时刻t
    """
    

## Numpy 第五题
有一个列表X,里面的元素可能是数，包含数的list,或者数值型np.array。请编一个函数把它转换为一维np.array数据。 比如将X=[[1,[2,[4,9]]],np.array([[1,2],[3,4]])]转换为：np.array([1,2,4,9,,1,2,3,4])。注意，列表X的嵌套层数可以是任意的

In [17]:
def solution(x):
    """
    有一个列表X,里面的元素可能是数，包含数的list,或者数值型np.array。请编一个函数把它转换为一维np.array数据。 比如将X=[[1,[2,[4,9]]],np.array([[1,2],[3,4]])]转换为：np.array([1,2,4,9,,1,2,3,4])。注意，列表X的嵌套层数可以是任意的
    """
    #使用递归或者循环，感觉有点像tree结构
    if isinstance(x,np.ndarray):
        return x.flatten()#使用flatten进行展平
    elif isinstance(x,list):
        output=[]
        for i in x:
            output.extend(solution(i))
        return np.array(output)
    else:#是数字
        return np.array([x])

In [18]:
#test
X=[[1,[2,[4,9]]],np.array([[1,2],[3,4]])]
print(X,'\n')
solution(X)

[[1, [2, [4, 9]]], array([[1, 2],
       [3, 4]])] 



array([1, 2, 4, 9, 1, 2, 3, 4])

## Pandas 第一题
将A1.csv-A5.csv 读入合并，同一个股票合并为一行。注意，这些表格中都有**相同的代码和名称列**,可以用它们作为index。也可能有一些冗余的列和行，对数据进行清理。

In [163]:
import os
import sys

import numpy as np
from numpy.random import randn
from pandas import Series, DataFrame
import pandas as pd

In [164]:
%pwd

'c:\\Users\\16017\\Desktop\\Dropbox\\金融数据分析导引\\Guide_to_financial_data_analysis\\hw\\hw2'

In [165]:
#读入文件，同时调整所有的NAN
missing_values=['NAN','--  ']#乐！原来后面还有两个空格！
df1=pd.read_csv('A1.csv',encoding='ANSI',na_values=missing_values)
df2=pd.read_csv('A2.csv',encoding='ANSI',na_values=missing_values)
df3=pd.read_csv('A3.csv',encoding='ANSI',na_values=missing_values)
df4=pd.read_csv('A4.csv',encoding='ANSI',na_values=missing_values)
df5=pd.read_csv('A5.csv',encoding='ANSI',na_values=missing_values)

In [166]:
#删除掉df2的'未匹配量'一列
df2.drop(labels='未匹配量',axis=1,inplace=True)
#清理数据
df1.dropna(axis=0,how='any',inplace=True)
df2.dropna(axis=0,how='any',inplace=True)
df3.dropna(axis=0,how='any',inplace=True)
df4.dropna(axis=0,how='any',inplace=True)
df5.dropna(axis=0,how='any',inplace=True)

In [167]:
#合并
output=pd.merge(df1,df2,on=['代码','名称'])
output=pd.merge(output,df3,on=['代码','名称'])
output=pd.merge(output,df4,on=['代码','名称'])
output=pd.merge(output,df5,on=['代码','名称'])

In [168]:
output

代码     名称  收入同比%%  利润同比%%  营业利润率%%    市销率    市净率     市现率   市盈(动)  \
0     000002  万  科Ａ   22.72    0.77    17.35   3.13   1.80  -23.08   16.21   
1     000004   国农科技  117.08  125.75    10.98  36.85  26.93 -337.10  905.17   
2     000006   深振业Ａ  311.53  425.18    17.93   6.29   3.01  -20.19   24.66   
3     000008   神州高铁  245.04  710.43    16.21  33.02   5.90 -164.80  117.66   
4     000009   中国宝安    9.97  -48.53    11.10   7.82   4.18 -194.41   65.87   
...      ...    ...     ...     ...      ...    ...    ...     ...     ...   
1823  603030   全筑股份    0.00    0.00     3.31   3.70   3.91  -21.72   74.98   
1824  603066   音飞储存    0.00    0.00    13.64  13.16   3.93   59.57   54.43   
1825  603085   天成自控    0.00    0.00    12.01  18.16   7.24  261.55   84.79   
1826  603088   宁波精达   -4.26  -25.21    14.35  27.66   6.55 -145.39   98.36   
1827  603100   川仪股份   -7.46   -3.65     4.80   2.94   2.63  -58.93   31.46   

               总金额  ...    每股收益  每股净资 调整后净资  每股公积  每股未分配    权益比  \
0     3.218100e+09  ...  0.439㈡  7.90   0.0  0.75   3.74  16.25   
1     1.750940e+08  ...  0.014㈡  0.97   0.0  0.01  -0.17  23.37   
2     5.046951e+08  ...  0.191㈡  3.14   0.0  0.36   1.00  35.97   
3     1.744046e+08  ...  0.087㈡  3.47   0.0  2.40   0.06  85.10   
4     9.347557e+08  ...  0.074㈡  2.35   0.0  0.32   0.91  24.35   
...            ...  ...     ...   ...   ...   ...    ...    ...   
1823  4.422784e+07  ...  0.160㈡  4.95   0.0  2.17   1.64  39.03   
1824  1.401917e+08  ...  0.330㈡  6.93   0.0  3.72   1.90  79.72   
1825  2.073511e+08  ...  0.220㈡  3.86   0.0  1.42   1.31  65.91   
1826  6.555792e+07  ...  0.187㈡  5.62   0.0  2.95   1.43  78.26   
1827  8.680403e+07  ...  0.186㈡  4.45   0.0  1.79   1.32  43.69   

                净益率%%  销售毛利率%%     今开  净利润率%%  
0               5.55㈡    30.45  13.77    9.64  
1               1.49㈡    35.95  27.00    2.04  
2               6.09㈡    33.74   8.85   12.76  
3               2.51㈡    43.90  20.02   14.03  
4               3.17㈡    35.41   9.20    5.94  
...               ...      ...    ...     ...  
1823            2.61㈡    13.52  19.01    2.47  
1824            3.61㈡    32.90  26.01   12.09  
1825            4.27㈡    31.96  28.30   10.71  
1826            3.33㈡    36.74  33.85   14.06  
1827            4.18㈡    26.38  11.75    4.68  

[1828 rows x 71 columns]

## Pandas 第二题
按"细分行业" 将资产分组 
+ 统计平均市盈率，平均价格；
+ 用总资产作权重，计算加权市盈率和加权平均价格；
+ 用流通市值作权重，计算加权市盈率和加权平均价格；

In [201]:
#统计平均市盈率，平均价格
grouped=output.groupby(output['细分行业'])

grouped1=grouped['市盈(动)']
means1=grouped1.mean()
print('按"细分行业" 将资产分组，平均市盈率是：\n\n',means1,'\n\n')

grouped2=grouped['均价']
means2=grouped2.mean()
print('按"细分行业" 将资产分组，平均价格是：\n\n',means2,'\n\n')

按"细分行业" 将资产分组，平均市盈率是：

 细分行业
专用机械    133.292679
中成药     163.449091
乳制品      53.892857
互联网     133.212143
仓储物流    120.127500
           ...    
铝       142.161333
陶瓷       33.695000
食品       56.944643
饲料      140.948000
黄金      199.201667
Name: 市盈(动), Length: 107, dtype: float64 


按"细分行业" 将资产分组，平均价格是：

 细分行业
专用机械    24.790714
中成药     22.401636
乳制品     18.245714
互联网     45.569286
仓储物流    19.436667
          ...    
铝       13.249333
陶瓷      22.270000
食品      17.726071
饲料      13.466000
黄金      10.318333
Name: 均价, Length: 107, dtype: float64 




In [202]:
#用总资产作权重，计算加权市盈率和加权平均价格
grouped=output.groupby(output['细分行业'])
weighted_mean1=lambda x : (x['市盈(动)']*x['总资产(万)']).sum()/x['总资产(万)'].sum()
weighted_mean2=lambda x : (x['均价']*x['总资产(万)']).sum()/x['总资产(万)'].sum()
result1=grouped.apply(weighted_mean1)
result2=grouped.apply(weighted_mean2)
print('按"细分行业" 将资产分组，用总资产作权重，加权市盈率是：\n\n',result1,'\n\n')
print('按"细分行业" 将资产分组，用总资产作权重，加权平均价格是：\n\n',result2,'\n\n')

按"细分行业" 将资产分组，用总资产作权重，加权市盈率是：

 细分行业
专用机械    140.687367
中成药      61.669138
乳制品      37.459924
互联网      74.351642
仓储物流     39.626051
           ...    
铝       956.643949
陶瓷       33.553590
食品       40.945880
饲料      157.019441
黄金      123.369481
Length: 107, dtype: float64 


按"细分行业" 将资产分组，用总资产作权重，加权平均价格是：

 细分行业
专用机械    16.295397
中成药     23.344972
乳制品     15.377747
互联网     35.137202
仓储物流    30.276403
          ...    
铝        6.016310
陶瓷      22.052929
食品      16.832933
饲料      12.111284
黄金       7.489810
Length: 107, dtype: float64 




In [177]:
#用流通市值作权重，计算加权市盈率和加权平均价格
#但是需要把含有单位的字符串，删去单位，然后转换数据类型
change1 = lambda x : float(((x[::-1])[1:])[::-1])
import copy
output1=copy.deepcopy(output)#为了防止改变了output
output1['流通市值']=output1['流通市值'].apply(change1)

In [212]:
grouped=output1.groupby(output1['细分行业'])
weighted_mean1=lambda x : (x['市盈(动)']*x['流通市值']).sum()/x['流通市值'].sum()
weighted_mean2=lambda x : (x['均价']*x['流通市值']).sum()/x['流通市值'].sum()
result3=grouped.apply(weighted_mean1)
result4=grouped.apply(weighted_mean2)
print('按"细分行业" 将资产分组，用流通市值作权重，加权市盈率是：\n\n',result3,'\n\n')
print('按"细分行业" 将资产分组，用流通市值作权重，加权平均价格是：\n\n',result4,'\n\n')

按"细分行业" 将资产分组，用流通市值作权重，加权市盈率是：

 细分行业
专用机械    333.716150
中成药      86.514999
乳制品      28.867495
互联网      99.679885
仓储物流     61.466999
           ...    
铝       589.054637
陶瓷       31.321731
食品       41.428019
饲料      119.954712
黄金      138.581972
Length: 107, dtype: float64 


按"细分行业" 将资产分组，用流通市值作权重，加权平均价格是：

 细分行业
专用机械    23.192580
中成药     29.174061
乳制品     15.896949
互联网     32.956778
仓储物流    14.981080
          ...    
铝        7.264917
陶瓷      18.626926
食品      19.046806
饲料      13.341803
黄金       8.100610
Length: 107, dtype: float64 




## Pandas 第三题
按"地区" 将资产分组，重新计算2中问题

In [215]:
#统计平均市盈率，平均价格
grouped=output.groupby(output['地区'])

grouped1=grouped['市盈(动)']
means3=grouped1.mean()
print('按"地区" 将资产分组，平均市盈率是：\n\n',means3,'\n\n')

grouped2=grouped['均价']
means4=grouped2.mean()
print('按"地区" 将资产分组，平均价格是：\n\n',means4,'\n\n')

按"地区" 将资产分组，平均市盈率是：

 地区
上海      140.092013
云南      140.537500
内蒙       57.360769
北京      193.619893
吉林      165.815385
四川      227.758030
天津       95.922500
宁夏     6619.164000
安徽       74.701667
山东      180.766579
山西      366.651818
广东      152.845933
广西      301.376500
新疆       77.984286
江苏      108.626216
江西       80.198696
河北      139.544324
河南      287.815625
浙江      109.961787
海南      344.346667
深圳      161.572154
湖北      143.556786
湖南      127.885625
甘肃       81.461429
福建      148.513559
西藏       91.743750
贵州      152.519375
辽宁       90.684146
重庆       45.070800
陕西      469.623043
青海      697.635000
黑龙江      52.473158
Name: 市盈(动), dtype: float64 


按"地区" 将资产分组，平均价格是：

 地区
上海     17.730940
云南     21.205625
内蒙     13.213846
北京     21.714545
吉林     17.042308
四川     20.206970
天津     13.679643
宁夏     10.550000
安徽     13.706296
山东     14.911842
山西     12.471818
广东     17.153600
广西     16.452000
新疆     11.180952
江苏     16.698162
江西     17.189130
河北     14.855676
河南     15.927500
浙江    

In [216]:
#用总资产作权重，计算加权市盈率和加权平均价格
grouped=output.groupby(output['地区'])
weighted_mean1=lambda x : (x['市盈(动)']*x['总资产(万)']).sum()/x['总资产(万)'].sum()
weighted_mean2=lambda x : (x['均价']*x['总资产(万)']).sum()/x['总资产(万)'].sum()
result5=grouped.apply(weighted_mean1)
result6=grouped.apply(weighted_mean2)
print('按"地区" 将资产分组，用总资产作权重，加权市盈率是：\n\n',result5,'\n\n')
print('按"地区" 将资产分组，用总资产作权重，加权平均价格是：\n\n',result6,'\n\n')

按"地区" 将资产分组，用总资产作权重，加权市盈率是：

 地区
上海      40.244850
云南     147.981068
内蒙      37.909637
北京      60.742973
吉林      93.306543
四川      93.524538
天津      64.477131
宁夏     581.088270
安徽      37.694517
山东     130.308601
山西     155.888651
广东      29.895743
广西      74.275663
新疆      35.953275
江苏     139.906052
江西      62.618065
河北     135.743853
河南     116.965191
浙江      70.561095
海南     140.344731
深圳      43.046237
湖北      74.525167
湖南      81.915689
甘肃      87.923483
福建      58.615814
西藏      78.430471
贵州      93.490725
辽宁      57.367854
重庆      25.633514
陕西     295.964154
青海      92.373555
黑龙江     31.695681
dtype: float64 


按"地区" 将资产分组，用总资产作权重，加权平均价格是：

 地区
上海     13.345892
云南     18.433702
内蒙      9.820733
北京      9.944571
吉林     12.838673
四川     12.634035
天津     13.129212
宁夏     10.505307
安徽     13.182581
山东     10.845851
山西      6.941386
广东     12.534784
广西     11.407796
新疆      9.753349
江苏     14.639143
江西     13.752074
河北     11.924748
河南     12.667649
浙江     12.654831
海南      5.820123

In [184]:
#用流通市值作权重，计算加权市盈率和加权平均价格
#但是需要把含有单位的字符串，删去单位，然后转换数据类型
change1 = lambda x : float(((x[::-1])[1:])[::-1])
import copy
output1=copy.deepcopy(output)#为了防止改变了output
output1['流通市值']=output1['流通市值'].apply(change1)

In [217]:
grouped=output1.groupby(output1['地区'])
weighted_mean1=lambda x : (x['市盈(动)']*x['流通市值']).sum()/x['流通市值'].sum()
weighted_mean2=lambda x : (x['均价']*x['流通市值']).sum()/x['流通市值'].sum()
result7=grouped.apply(weighted_mean1)
result8=grouped.apply(weighted_mean2)
print('按"地区" 将资产分组，用流通市值作权重，加权市盈率是：\n\n',result7,'\n\n')
print('按"地区" 将资产分组，用流通市值作权重，加权平均价格是：\n\n',result8,'\n\n')

按"地区" 将资产分组，用流通市值作权重，加权市盈率是：

 地区
上海       89.376589
云南       70.297277
内蒙       38.397136
北京       89.915696
吉林      119.212669
四川      138.627476
天津       68.430644
宁夏     8275.464842
安徽       48.454498
山东      144.796357
山西      240.482939
广东       75.043979
广西      171.253668
新疆       44.609234
江苏      116.520740
江西       84.131680
河北      111.608882
河南      161.765399
浙江       81.587045
海南      157.043098
深圳       79.943159
湖北       72.516270
湖南       86.075870
甘肃       99.027719
福建       88.582945
西藏       68.153581
贵州       65.997871
辽宁       67.869959
重庆       27.703092
陕西      436.803221
青海      321.729395
黑龙江      39.305872
dtype: float64 


按"地区" 将资产分组，用流通市值作权重，加权平均价格是：

 地区
上海      18.077170
云南      44.443943
内蒙      13.898170
北京      13.271512
吉林      18.463700
四川      16.431335
天津      15.870189
宁夏      11.908732
安徽      15.152813
山东      15.164031
山西       9.296313
广东      14.772749
广西      15.635164
新疆      10.377461
江苏      19.420696
江西      18.963561
河北      15.377702

## Pandas 第四题
将上述**计算结果**合并后存为csv文件

**计算结果**有：

按"细分行业" 将资产分组 
   + 统计平均市盈率，平均价格；means1，means2
   + 用总资产作权重，计算加权市盈率和加权平均价格；result1,result2
   + 用流通市值作权重，计算加权市盈率和加权平均价格；result3,result4
   
按"地区" 将资产分组 
   + 统计平均市盈率，平均价格；means3，means4
   + 用总资产作权重，计算加权市盈率和加权平均价格；result5,result6
   + 用流通市值作权重，计算加权市盈率和加权平均价格；result7,result8

In [220]:
out1=pd.concat([means1,means2,result1,result2,result3,result4],axis=1,ignore_index=False)
out1.columns=['平均市盈率','平均价格','总资产加权市盈率','总资产加权平均价格','流通市值加权市盈率','流通市值加权平均价格']
out1

平均市盈率       平均价格    总资产加权市盈率  总资产加权平均价格   流通市值加权市盈率  流通市值加权平均价格
细分行业                                                                      
专用机械  133.292679  24.790714  140.687367  16.295397  333.716150   23.192580
中成药   163.449091  22.401636   61.669138  23.344972   86.514999   29.174061
乳制品    53.892857  18.245714   37.459924  15.377747   28.867495   15.896949
互联网   133.212143  45.569286   74.351642  35.137202   99.679885   32.956778
仓储物流  120.127500  19.436667   39.626051  30.276403   61.466999   14.981080
...          ...        ...         ...        ...         ...         ...
铝     142.161333  13.249333  956.643949   6.016310  589.054637    7.264917
陶瓷     33.695000  22.270000   33.553590  22.052929   31.321731   18.626926
食品     56.944643  17.726071   40.945880  16.832933   41.428019   19.046806
饲料    140.948000  13.466000  157.019441  12.111284  119.954712   13.341803
黄金    199.201667  10.318333  123.369481   7.489810  138.581972    8.100610

[107 rows x 6 columns]

In [232]:
out2=pd.concat([means3,means4,result5,result6,result7,result8],axis=1,ignore_index=False)
out2.columns=['平均市盈率','平均价格','总资产加权市盈率','总资产加权平均价格','流通市值加权市盈率','流通市值加权平均价格']
out2

平均市盈率       平均价格    总资产加权市盈率  总资产加权平均价格    流通市值加权市盈率  流通市值加权平均价格
地区                                                                         
上海    140.092013  17.730940   40.244850  13.345892    89.376589   18.077170
云南    140.537500  21.205625  147.981068  18.433702    70.297277   44.443943
内蒙     57.360769  13.213846   37.909637   9.820733    38.397136   13.898170
北京    193.619893  21.714545   60.742973   9.944571    89.915696   13.271512
吉林    165.815385  17.042308   93.306543  12.838673   119.212669   18.463700
四川    227.758030  20.206970   93.524538  12.634035   138.627476   16.431335
天津     95.922500  13.679643   64.477131  13.129212    68.430644   15.870189
宁夏   6619.164000  10.550000  581.088270  10.505307  8275.464842   11.908732
安徽     74.701667  13.706296   37.694517  13.182581    48.454498   15.152813
山东    180.766579  14.911842  130.308601  10.845851   144.796357   15.164031
山西    366.651818  12.471818  155.888651   6.941386   240.482939    9.296313
广东    152.845933  17.153600   29.895743  12.534784    75.043979   14.772749
广西    301.376500  16.452000   74.275663  11.407796   171.253668   15.635164
新疆     77.984286  11.180952   35.953275   9.753349    44.609234   10.377461
江苏    108.626216  16.698162  139.906052  14.639143   116.520740   19.420696
江西     80.198696  17.189130   62.618065  13.752074    84.131680   18.963561
河北    139.544324  14.855676  135.743853  11.924748   111.608882   15.377702
河南    287.815625  15.927500  116.965191  12.667649   161.765399   16.795393
浙江    109.961787  16.511691   70.561095  12.654831    81.587045   16.912561
海南    344.346667   9.040833  140.344731   5.820123   157.043098    7.977382
深圳    161.572154  18.283308   43.046237  16.484728    79.943159   17.082925
湖北    143.556786  15.004464   74.525167  11.199301    72.516270   14.989248
湖南    127.885625  15.091042   81.915689  14.083046    86.075870   15.226616
甘肃     81.461429  10.406429   87.923483   9.045769    99.027719    9.286071
福建    148.513559  15.966780   58.615814  12.143148    88.582945   14.202433
西藏     91.743750  16.353750   78.430471  12.119334    68.153581   14.757472
贵州    152.519375  28.298750   93.490725  90.866502    65.997871  138.483456
辽宁     90.684146  14.256585   57.367854   8.042790    67.869959   12.772551
重庆     45.070800  14.088000   25.633514  10.526303    27.703092   11.940039
陕西    469.623043  14.471739  295.964154  18.007320   436.803221   18.829857
青海    697.635000  16.556667   92.373555  15.611069   321.729395   15.549516
黑龙江    52.473158  17.920000   31.695681  15.800187    39.305872   15.876270

In [238]:
out1.to_csv('output.csv')
out2.to_csv('output.csv',mode='a')#append在后面