In [1]:
import numpy as np

In [ ]:
np.lexsort?

In [6]:
a=[[3,3,8],[6,9,7],[3,3,2]]
b=np.array(a)
b

array([[3, 3, 8],
       [6, 9, 7],
       [3, 3, 2]])

In [16]:
index=np.lexsort((b[:,2],b[:,1],b[:,0]))
index

array([2, 0, 1], dtype=int64)

In [18]:
b[index]

array([[3, 3, 2],
       [3, 3, 8],
       [6, 9, 7]])