# 作业

1.  给定一个二维数组，每行是一个向量。找出所有不同的行。
比如： 

```x = np.array([[1., 2., 3.], [4., 5., 6.],[1., 2., 3.], [4., 5., 6.]]),则
x[:2]，即x的第0,1行，array([[ 1.,  2.,  3.],[ 4.,  5.,  6.]])就是要找到行。
```

备注：请不要直接调用numpy.unique

2.  a).产生正态数据数据向量 Z,长度为T， 建立一个二维数组，使其第一行为 (Z[0],Z[1],Z[2])，然后每一行都后移一位 （因此最后一行为 (Z[T-3],Z[T-2],Z[T-1] );b). 计算每列数据的样本均值，方差，各列之间的协方差。
 
3. a). 随机生成一个1000行50列二维数组，每个元素等概率取值0，1，2，并将该数组按第1列递增和第2列递减对每行排序，即先按第一列递增排序，然后在第一列每组中， 按第二列递减排序。 b). 编一个函数sortbycols(data,cols,descending)，实现行排序。给定参数 data是二维数值，cols是数或list,给出需要排序的列，descending是布尔值或布尔向量，如果是一个布尔值，则所有列都按该顺序排，如果descending是和cols等长的list，则各列按descending给定的顺序排。
4.  熟悉学习numpy中的现金流函数, np.pv,np.fv,np.nper,np.pmt,np.rate, 然后编制一个函数，计算给定现金流(array)，利率(array),任意时刻(t)的现金价值。

# 第一题
给定一个二维数组，每行是一个向量。找出所有不同的行。
比如： 

```x = np.array([[1., 2., 3.], [4., 5., 6.],[1., 2., 3.], [4., 5., 6.]]),则
x[:2]，即x的第0,1行，array([[ 1.,  2.,  3.],[ 4.,  5.,  6.]])就是要找到行。
```

In [1]:
import numpy as np
def check(arr):
    """ 输入一个二维数组，每行是一个向量，找出所有不同的行 """
    if isinstance(arr,np.ndarray) and len(a.shape)==1:
        print('The array only has one row.')
        return arr
    m=arr.shape[0]
    remark=np.zeros((m,1))
    for i in range(0,m):
        for j in range(0,m):
            if np.all(arr[i]==arr[j]):
                remark[i]+=1
    unique_rows=[]
    for i in range(0,m):
        if remark[i]==1:
            unique_rows.append(arr[i])
    return np.array(unique_rows)

# 第二题
+ a).产生正态数据数据向量 Z,长度为T， 建立一个二维数组，使其第一行为 (Z[0],Z[1],Z[2])，然后每一行都后移一位 （因此最后一行为 (Z[T-3],Z[T-2],Z[T-1] );

+ b). 计算每列数据的样本均值，方差，各列之间的协方差。

In [2]:
import numpy as np
def create(T):
    """
    产生正态数据数据向量 Z,长度为T， 建立一个二维数组，使其第一行为 (Z[0],Z[1],Z[2])，然后每一行都后移一位 （因此最后一行为 (Z[T-3],Z[T-2],Z[T-1] );
    """
    arr=np.random.randn(T)
    output=np.zeros((T-2,3))
    for i in range(0,T-2):
        output[i]=arr[i:i+3]
    print(output,'\n\n')
    print('每列数据的样本均值是\n',np.mean(output,axis=0),'\n\n')
    print('每列数据的样本方差是\n',np.var(output,axis=0),'\n\n')
    print('每列数据的样本协方差是\n',np.cov(output,rowvar=False))
    return 

# 第三题
+ a). 随机生成一个1000行50列二维数组，每个元素等概率取值0，1，2，并将该数组按第1列递增和第2列递减对每行排序，即先按第一列递增排序，然后在第一列每组中， 按第二列递减排序。
+ b). 编一个函数sortbycols(data,cols,descending)，实现行排序。给定参数 data是二维数值，cols是数或list,给出需要排序的列，descending是布尔值或布尔向量，如果是一个布尔值，则所有列都按该顺序排，如果descending是和cols等长的list，则各列按descending给定的顺序排。

In [3]:
#Solution1：这里理解为对第一列或者第二列进行排序的时候，其他的元素不会动
import numpy as np
arr=np.random.choice([0,1,2],size=(1000,50))
arr[:,0]=np.sort(arr[:,0])#对第一列进行递增排序
i=0
while i<=999:
    start,end=0,0
    if arr[i][0]==1:
        end=i-1
        arr[start:end,1]=np.sort(arr[start:end,1])[::-1]#对第一列是0的行的第二列进行递减排序
        start=i
    if arr[i][0]==2:
        end=i-1
        arr[start:end,1]=np.sort(arr[start:end,1])[::-1]#对第一列是1的行的第二列进行递减排序
        start=i
        arr[start:,1]=np.sort(arr[start:,1])[::-1]#对第一列是2的行的第二列进行递减排序
    i=i+1
print(arr)

[[0 2 2 ... 1 1 1]
 [0 2 1 ... 0 0 2]
 [0 2 0 ... 1 1 1]
 ...
 [2 0 0 ... 1 2 0]
 [2 0 1 ... 2 1 0]
 [2 0 0 ... 0 2 2]]


In [4]:
#Solution2：这里理解为对第一列或者第二列进行排序的时候，其他的元素会跟着动，也就是说，最开始在同一行的元素之间的位置是不变的
import numpy as np
arr=np.random.choice([0,1,2],size=(1000,50))

# 第四题
熟悉学习numpy中的现金流函数, np.pv,np.fv,np.nper,np.pmt,np.rate, 然后编制一个函数，计算给定现金流(array)，利率(array),任意时刻(t)的现金价值。

需要下载 numpy_financial 包
> pip install numpy_financial

In [5]:
import numpy_financial as npf

In [6]:
?npf.pv

Signature: npf.pv(rate, nper, pmt, fv=0, when='end')
Docstring:
Compute the present value.

Given:
 * a future value, `fv`
 * an interest `rate` compounded once per period, of which
   there are
 * `nper` total
 * a (fixed) payment, `pmt`, paid either
 * at the beginning (`when` = {'begin', 1}) or the end
   (`when` = {'end', 0}) of each period

Return:
   the value now

Parameters
----------
rate : array_like
    Rate of interest (per period)
nper : array_like
    Number of compounding periods
pmt : array_like
    Payment
fv : array_like, optional
    Future value
when : {{'begin', 1}, {'end', 0}}, {string, int}, optional
    When payments are due ('begin' (1) or 'end' (0))

Returns
-------
out : ndarray, float
    Present value of a series of payments or investments.

Notes
-----
The present value is computed by solving the equation::

 fv +
 pv*(1 + rate)**nper +
 pmt*(1 + rate*when)/rate*((1 + rate)**nper - 1) = 0

or, when ``rate = 0``::

 fv + pv + pmt * nper = 0

for `pv`, which