# 请先写出代码结果，然后运行代码，解释代码和结果

In [1]:
a = "100"
try:
    b = a + 2
except:
    print(str(a)+ " is not a number")
else:
    print(str(a)+ " is a number")
finally:
    print("done")

100 is not a number
done


In [2]:
import numpy as np
arr = np.arange(1,21,2)
print(arr)
print(np.sum(arr[3:5]))#不包含五

[ 1  3  5  7  9 11 13 15 17 19]
16


In [4]:
arr = np.arange(10)
print(arr)
arr_slice = arr[5:]
arr_slice[:] = 0
print(arr)
print(arr.sum())

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 0 0 0 0 0]
10


In [5]:
def make_fun(n): 
    return lambda x: 2*x+n   
f = make_fun(21) 
print(f(3)) 

27


In [6]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [7]:
data={'key' : ['a', 'a', 'b', 'b', 'a'], 
                'num' : np.arange(1,10,2)}
for x in data:
    print(x)    

key
num


In [11]:
from pandas import DataFrame
frame = DataFrame({ 'a': [0, 1, 0],'b': [4, 7, -3]})
print(frame)
sortbyab=frame.sort_values(by=['a', 'b'])
print(sortbyab)

   a  b
0  0  4
1  1  7
2  0 -3
   a  b
2  0 -3
0  0  4
1  1  7


In [9]:
frame.sort_values?

Signature:
frame.sort_values(
    by: 'IndexLabel',
    *,
    axis: 'Axis' = 0,
    ascending: 'bool | list[bool] | tuple[bool, ...]' = True,
    inplace: 'bool' = False,
    kind: 'str' = 'quicksort',
    na_position: 'str' = 'last',
    ignore_index: 'bool' = False,
    key: 'ValueKeyFunc' = None,
) -> 'DataFrame | None'
Docstring:
Sort by the values along either axis.

Parameters
----------
        by : str or list of str
            Name or list of names to sort by.

            - if `axis` is 0 or `'index'` then `by` may contain index
              levels and/or column labels.
            - if `axis` is 1 or `'columns'` then `by` may contain column
              levels and/or index labels.
axis : {0 or 'index', 1 or 'columns'}, default 0
     Axis to be sorted.
ascending : bool or list of bool, default True
     Sort ascending vs. descending. Specify list for multiple sort
     orders.  If this is a list of bools, must match the length of
     the by.
inplace : bool, default Fals

In [15]:
import pandas as pd
df1=DataFrame(np.arange(6).reshape(3,2),index=['a','b','c'],columns=['one','two'])
print(df1,'\n')
df2=DataFrame(5+np.arange(2),index=['a','c'],columns=['three'])
print(df2,'\n')
df3=pd.concat([df1,df2],axis=1)
print(df3,'\n')
print(df3.iloc[1].values) 

   one  two
a    0    1
b    2    3
c    4    5 

   three
a      5
c      6 

   one  two  three
a    0    1    5.0
b    2    3    NaN
c    4    5    6.0 

[ 2.  3. nan]


In [16]:
import numpy as np
a=np.array([1,2,3]*2)*2 
print(a)

[2 4 6 2 4 6]


In [18]:
Z = np.zeros((3,3))
print(Z,'\n')
Z += np.arange(3)
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]


In [19]:
from pandas import DataFrame, Series
df = DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                'key2' : ['one', 'two', 'one', 'two', 'one'],
                'data1' : np.arange(0,10,2),
                'data2' : np.arange(1,10,2)})
print(df)
grouped = df['data1'].groupby(df['key1'])
x=grouped.sum()
print(x)

  key1 key2  data1  data2
0    a  one      0      1
1    a  two      2      3
2    b  one      4      5
3    b  two      6      7
4    a  one      8      9
key1
a    10
b    10
Name: data1, dtype: int32


In [25]:
df = DataFrame({'data1' : np.arange(0,10,4),
                'data2' : np.arange(1,10,3)},index=pd.date_range('2021-10-21', periods=3, freq='B'))
print(df)
df1=  DataFrame({'data1' : np.arange(0,5),
                'data3' : np.arange(0,5)},index=pd.date_range('2021-10-21', periods=5, freq='D'))
print(df1)
print(df+df1)
(df+df1).isnull().sum()

            data1  data2
2021-10-21      0      1
2021-10-22      4      4
2021-10-25      8      7
            data1  data3
2021-10-21      0      0
2021-10-22      1      1
2021-10-23      2      2
2021-10-24      3      3
2021-10-25      4      4
            data1  data2  data3
2021-10-21    0.0    NaN    NaN
2021-10-22    5.0    NaN    NaN
2021-10-23    NaN    NaN    NaN
2021-10-24    NaN    NaN    NaN
2021-10-25   12.0    NaN    NaN


data1    2
data2    5
data3    5
dtype: int64

In [30]:
data = {'a': 20, 'b': 10,'c':30}
indx1 = ['a', 'b']
obj3 = Series(data,index=indx1)
print(obj3,'\n')
indx2 = ['a', 'c']
obj4 = Series(data, index=indx2)
print(obj4,'\n')
out1=obj3+obj4
print(out1,'\n')
print(out1.dropna())

a    20
b    10
dtype: int64 

a    20
c    30
dtype: int64 

a    40.0
b     NaN
c     NaN
dtype: float64 

a    40.0
dtype: float64


In [32]:
from datetime import datetime
from datetime import timedelta
start = datetime(2011, 1, 7)
print(start,'\n')
d=start + timedelta(11)
print(d)
# 只需说明表示什么时间，不管格式

2011-01-07 00:00:00 

2011-01-18 00:00:00


In [38]:
a = [1,2]
b = [3,4]
print([a.append(b),a.extend(b),a+b])
#a.append(b) 的返回值是None

[None, None, [1, 2, [3, 4], 3, 4, 3, 4]]


In [3]:
a = [1,2]
b = [3,4]
a.extend(b)
print(a)

[1, 2, 3, 4]


In [46]:
import numpy as np
print(np.identity(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [47]:
ts1 = Series(np.arange(10),
             index=pd.date_range('2021-10-21', periods=10, freq='B'))
ts1.resample('W-THU').sum()

2021-10-21     0
2021-10-28    15
2021-11-04    30
Freq: W-THU, dtype: int32