In [2]:
from numpy.random import randn #产生正态随机数的函数
import numpy as np #简便书写

In [3]:
np.array([3.4, 5.5])#生成array 数据的函数

array([3.4, 5.5])

In [4]:
data = randn(2,3)
print(data)
print(data.shape) #输出array格式的数据的维数
print(data.dtype) #输出array格式的的数据的类别
b = [[2,]]
np.array(b).shape #说明空的会被省略掉

[[ 1.11050615 -0.48876071 -1.89033779]
 [-0.72974251  0.24283434 -0.0853379 ]]
(2, 3)
float64


(1, 1)

In [5]:
a=np.array([1,2,3])
b=np.array([[1,]])
c=np.array([[1,0,0],[0,1,2]])
print(a,a.shape,a.dtype,end='\n\n')
print(b,b.shape,b.dtype,end='\n\n')
print(c,c.shape,c.dtype,end='\n\n')

[1 2 3] (3,) int32

[[1]] (1, 1) int32

[[1 0 0]
 [0 1 2]] (2, 3) int32



In [6]:
print(np.arange(15),end='\n\n') #输出等差数列，默认值0-15，不包含mxa=15，默认步长为1
print(np.arange(2,15),end='\n\n') #输出等差数列，从2-15，不包含15，默认步长为1
print(np.arange(2,15,2),end='\n\n') #输出等差数列，从2-15，不包含15，步长设定为2
print(np.arange(2,15,1.5),end='\n\n') #步长设定为1.5

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 2  4  6  8 10 12 14]

[ 2.   3.5  5.   6.5  8.   9.5 11.  12.5 14. ]



In [7]:
print(np.linspace(0,1,11),end='\n\n')#从0-11，不包含11，设定一共有11个
print(np.linspace(0,1,11, endpoint = False), end='\n\n')
print(np.linspace(0,1,11, endpoint = True), end='\n\n')#可以设置是否包含max
print(np.linspace(0,1,12),end='\n\n')

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]



In [8]:
data1=[6,7.8,8.9,33]
arr1=np.array(data1)
print(arr1,arr1.shape,arr1.dtype)

[ 6.   7.8  8.9 33. ] (4,) float64


In [9]:
data2=[[1,2,3.0,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2,arr2.shape,arr2.dtype)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]] (2, 4) float64


In [10]:
#使用reshape来改变维数
print(arr2,arr2.shape,arr2.dtype,end='\n\n')
b=arr2.reshape((1,8))
print(b,b.shape,b.dtype,end='\n\n')
b=arr2.reshape((4,2))
print(b,b.shape,b.dtype,end='\n\n')


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]] (2, 4) float64

[[1. 2. 3. 4. 5. 6. 7. 8.]] (1, 8) float64

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]] (4, 2) float64



In [11]:
a=np.zeros(10,dtype='int')
print(a,a.shape,a.dtype)
a=np.zeros(10,dtype='float')
print(a,a.shape,a.dtype)

[0 0 0 0 0 0 0 0 0 0] (10,) int32
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,) float64


In [12]:
b=np.ones((2,3),dtype='int')
print(b,b.shape,b.dtype)
b=np.ones((2,3),dtype='float')
print(b,b.shape,b.dtype)

[[1 1 1]
 [1 1 1]] (2, 3) int32
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3) float64


In [13]:
c=np.identity(2)#单位矩阵(方阵)
print(c,c.shape,c.dtype,end='\n\n')
d=np.eye(4,9)
print(d,d.shape,d.dtype)

[[1. 0.]
 [0. 1.]] (2, 2) float64

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]] (4, 9) float64


In [14]:
arr = np.array([1,2,3,4,5],dtype=np.int32)
print(arr,arr.shape,arr.dtype)

[1 2 3 4 5] (5,) int32


In [15]:
#使用astype去修改类型
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.shape,float_arr.dtype)

[1. 2. 3. 4. 5.] (5,) float64


In [16]:
arr=np.array([3.7,1.2,0.5,12.7,5.6])
c=arr.astype(np.int32)
print(c,c.shape,c.dtype)

[ 3  1  0 12  5] (5,) int32


In [17]:
c=numeric_strings = np.array(['1.25', '42'],dtype=str)
print(c,c.shape,c.dtype)
c=c.astype(float)
print(c,c.shape,c.dtype)

['1.25' '42'] (2,) <U4
[ 1.25 42.  ] (2,) float64


In [18]:
arr=np.array(([1,2,3],[4,5,6]),dtype=float)
print(arr,end='\n\n')
print(arr*arr,end='\n\n')#对应元素相乘
print(arr*arr-arr,end='\n\n')
print(1/arr,end='\n\n')
print(arr*2,end='\n\n')
print(arr**2,end='\n\n')#对应元素平方

[[1. 2. 3.]
 [4. 5. 6.]]

[[ 1.  4.  9.]
 [16. 25. 36.]]

[[ 0.  2.  6.]
 [12. 20. 30.]]

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]]

[[ 1.  4.  9.]
 [16. 25. 36.]]



In [19]:
arr=np.arange(10)
print(arr,arr.shape,arr.dtype)
print(arr[5:8])
arr[5:8] = 12
print(arr,arr.shape,arr.dtype)

[0 1 2 3 4 5 6 7 8 9] (10,) int32
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9] (10,) int32


In [20]:
arr=np.arange(10)
arr_slice=arr[5:8]
print(id(arr_slice), id(arr[5:8]),)
print(arr_slice is arr[5:8],'\n',arr_slice == arr[5:8] )
arr_slice[1]=12345
print(arr,'\n', arr_slice)

2177465976656 2177465975216
False 
 [ True  True  True]
[    0     1     2     3     4     5 12345     7     8     9] 
 [    5 12345     7]


原因：
> object（对象） 与 location（地址） 并不相同
+ 一个对象可以是一个指针，例如对象A是个指针，它的内容是->B，其中B是一个存储空间；C也可以是个指针，内容也是->B，这时候它们是两个不同的对象，指向同一个存储空间
> 但实际上，切片slice，只是创造了一个视图，其实指向的地址还是不一样

In [21]:
print(arr,'\n',arr_slice)
arr_slice[:]=64
print(arr,'\n',arr_slice)

[    0     1     2     3     4     5 12345     7     8     9] 
 [    5 12345     7]
[ 0  1  2  3  4 64 64 64  8  9] 
 [64 64 64]


In [22]:
a_list=list(range(10))
list_slice=a_list[5:8]
print(a_list is list_slice)
list_slice[1] = 12345
print(a_list, '\n', list_slice)

False
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
 [5, 12345, 7]


In [23]:
a=[1,2,3,[1,2]]
b=a[3][1]
print(b is a[3][1])
b=1000
print(a,'\n',b)

True
[1, 2, 3, [1, 2]] 
 1000


In [24]:
import copy
c=copy.deepcopy(a)
print(a is c, a==c)

False True


In [25]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d,arr2d.shape,arr2d.dtype,end='\n\n')
print(arr2d,'\n\n',arr2d[0],'\n\n',arr2d[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) int32

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [1 2 3] 

 2


In [26]:
print(arr2d,end='\n\n')
print(arr2d[:][0] , '\n\n', arr2d[:,0],end='\n\n')
print(arr2d[:][0]==arr2d[:,0], arr2d[:][0] is arr2d[:,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3] 

 [1 4 7]

[ True False False] False


+ arr2d[:][0] is equivalent to arr2d[0] instead of arr2d[:,0]

In [27]:
#二维数组切片也传输地址
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d,end='\n\n')
b = arr2d[2]
print(b,b is arr2d[2],end='\n\n')
arr2d[2] = 3
print('arr2d[2]=',arr2d[2],'\n\n','arr2d=\n',arr2d,end='\n\n')
#二维数组的切片一定会传地址
c=arr2d[0][:2]
print(c is arr2d[0][:2], c, end='\n\n')
arr2d[0][:2]=1000
print('arr2d[0][:2]=',arr2d[0][:2],'\n','arr2d=\n',arr2d,end='\n\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[7 8 9] False

arr2d[2]= [3 3 3] 

 arr2d=
 [[1 2 3]
 [4 5 6]
 [3 3 3]]

False [1 2]

arr2d[0][:2]= [1000 1000] 
 arr2d=
 [[1000 1000    3]
 [   4    5    6]
 [   3    3    3]]



In [28]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d,'\n\n',arr3d.shape,'\n\n',arr3d.dtype)
print('arr3d[0]=',arr3d[0])
print('arr3d[0][0]=',arr3d[0][0])
print('arr3d[0][0][0]=',arr3d[0][0][0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

 (2, 2, 3) 

 int32
arr3d[0]= [[1 2 3]
 [4 5 6]]
arr3d[0][0]= [1 2 3]
arr3d[0][0][0]= 1


+ 数组拷贝
> 要生成新的对象(传递数值)，而不是传递地址，需要用到copy函数

In [29]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d,arr2d.shape,arr2d.dtype,end='\n\n')

old_values=arr2d.copy()
old_1=copy.deepcopy(arr2d)
print(old_values)

arr2d[0][:]=999
print(arr2d,'\n',old_values,'\n',old_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) int32

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[999 999 999]
 [  4   5   6]
 [  7   8   9]] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
print(arr)
print(arr[1:6],'\n')

print(arr2d)
print(arr2d[:2],'\n')

print(arr2d[1, :2],'\n')

arr2d[:2 , 1: ]=0
print(arr2d)

[ 0  1  2  3  4 64 64 64  8  9]
[ 1  2  3  4 64] 

[[999 999 999]
 [  4   5   6]
 [  7   8   9]]
[[999 999 999]
 [  4   5   6]] 

[4 5] 

[[999   0   0]
 [  4   0   0]
 [  7   8   9]]


In [31]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = randn(7,4)
print(names,'\n\n',data,'\n')

print(names == 'Bob','\n') #返回的逻辑判断是对所有元素逐个判断之后合并起来的array变量
print(data[names == 'Bob'],'\n')#输出的是取了True的行，其他都没有输出
print(data[names == 'Bob',2:],'\n')#第三列到最后
print(data[names == 'Bob',3:],'\n')#第四列

print(names != 'Bob')
print(data[names != 'Bob'],'\n')

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] 

 [[ 0.62385572  1.60226246 -0.72252159 -0.04559342]
 [ 0.3337796  -1.60919439 -0.97578699  0.54728682]
 [ 0.458751    0.27385572  0.8399314  -0.48927054]
 [-0.2341917  -0.12779977 -0.19851351 -0.01660679]
 [-0.37751472 -1.17983226 -1.23789415 -0.06258989]
 [ 0.53242904 -0.28300355 -0.26773259  0.19337347]
 [ 0.2387453  -1.76764931  0.20434919  2.76613555]] 

[ True False False  True False False False] 

[[ 0.62385572  1.60226246 -0.72252159 -0.04559342]
 [-0.2341917  -0.12779977 -0.19851351 -0.01660679]] 

[[-0.72252159 -0.04559342]
 [-0.19851351 -0.01660679]] 

[[-0.04559342]
 [-0.01660679]] 

[False  True  True False  True  True  True]
[[ 0.3337796  -1.60919439 -0.97578699  0.54728682]
 [ 0.458751    0.27385572  0.8399314  -0.48927054]
 [-0.37751472 -1.17983226 -1.23789415 -0.06258989]
 [ 0.53242904 -0.28300355 -0.26773259  0.19337347]
 [ 0.2387453  -1.76764931  0.20434919  2.76613555]] 



In [32]:
mask = (names == 'Bob') | (names == 'Will')  # 还有&
print(mask,'\n')
print(data[mask],'\n')

[ True False  True  True  True False False] 

[[ 0.62385572  1.60226246 -0.72252159 -0.04559342]
 [ 0.458751    0.27385572  0.8399314  -0.48927054]
 [-0.2341917  -0.12779977 -0.19851351 -0.01660679]
 [-0.37751472 -1.17983226 -1.23789415 -0.06258989]] 



In [33]:
print(data,'\n')
print(data < 0 ,'\n')

data[data<0] = 0
print ( data,'\n')

[[ 0.62385572  1.60226246 -0.72252159 -0.04559342]
 [ 0.3337796  -1.60919439 -0.97578699  0.54728682]
 [ 0.458751    0.27385572  0.8399314  -0.48927054]
 [-0.2341917  -0.12779977 -0.19851351 -0.01660679]
 [-0.37751472 -1.17983226 -1.23789415 -0.06258989]
 [ 0.53242904 -0.28300355 -0.26773259  0.19337347]
 [ 0.2387453  -1.76764931  0.20434919  2.76613555]] 

[[False False  True  True]
 [False  True  True False]
 [False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [False  True  True False]
 [False  True False False]] 

[[0.62385572 1.60226246 0.         0.        ]
 [0.3337796  0.         0.         0.54728682]
 [0.458751   0.27385572 0.8399314  0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.53242904 0.         0.         0.19337347]
 [0.2387453  0.         0.20434919 2.76613555]] 



In [34]:
data [ names != 'Joe'] = 7
print(data)

[[7.         7.         7.         7.        ]
 [0.3337796  0.         0.         0.54728682]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [0.53242904 0.         0.         0.19337347]
 [0.2387453  0.         0.20434919 2.76613555]]


In [35]:
np.empty([2,2],dtype=int)

array([[16843009, 16843009],
       [16843009, 16843009]])

+ Keep in mind that the values in the array are essentially garbage values until you explicitly assign values to them.

In [36]:
?np.empty  # 使用 ipython 中的 ? 进行索引说明

Object `np.empty  # 使用 ipython 中的 ? 进行索引说明` not found.


In [37]:
arr = np.empty([8,4])
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [38]:
#可以同时索引多行
arr[[4,5,6,0]]

array([[4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [0., 0., 0., 0.]])

In [39]:
arr[[-1,-2,0,2]] #-1就是倒数第一行，这里是第八行(7)

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [0., 0., 0., 0.],
       [2., 2., 2., 2.]])

In [51]:
arr = np.arange(32).reshape((8,4))
print(arr,'\n')

b = arr[[1,5,7,2]]
print(b,'\n')

c = arr[:,[0,3,1,2]]
print(c,'\n')

d = arr[[1,5,7,2],:][: , [0,3,1,2]]
print(d,'\n')

e = arr[[1,5,7,2],[0,3,1,2]]
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]] 

[[ 0  3  1  2]
 [ 4  7  5  6]
 [ 8 11  9 10]
 [12 15 13 14]
 [16 19 17 18]
 [20 23 21 22]
 [24 27 25 26]
 [28 31 29 30]] 

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]] 

[ 4 23 29 10]


In [52]:
arr=np.arange(15).reshape((3,5))
print(arr,'\n\n',arr.T,'\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]] 



In [53]:
arr=np.random.randn(6,3)
np.dot(arr.T, arr)#真正的矩阵乘法

array([[ 9.86812313,  6.23188435, -5.24650373],
       [ 6.23188435,  7.59991319, -5.96056109],
       [-5.24650373, -5.96056109,  5.83684319]])

In [63]:
arr = np.arange(16).reshape((2,2,4))
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [65]:
arr = np.arange(10)
print(arr,'\n')
print(np.sqrt(arr),'\n')
print(np.exp(arr),'\n')

[0 1 2 3 4 5 6 7 8 9] 

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03] 



In [68]:
x=randn(8)
y=randn(8)
print(x,y,'\n')
print(np.maximum(x,y))#生成二维元组，对应位置取x,y的最大值

[ 1.47937861  0.16363015  0.07632625 -0.0421127  -0.28039442  2.29488357
  0.14705189 -1.09663359] [-0.0246139   0.51394298 -0.02285327 -0.7409974   0.55570039 -0.53417301
  0.08019585  0.51399377] 

[ 1.47937861  0.51394298  0.07632625 -0.0421127   0.55570039  2.29488357
  0.14705189  0.51399377]


In [77]:
arr = randn(7)*5
print(arr,'\n')
print(np.modf(arr))

print('test:\n')
arr = np.arange(15)+0.67
print('arr=',arr,'\n')
print('np.modf(arr)=',np.modf(arr),'\n')

[ 5.43842255 -8.73812197 -2.60850054 11.03932393  4.72960262 -2.20181843
 -4.81009494] 

(array([ 0.43842255, -0.73812197, -0.60850054,  0.03932393,  0.72960262,
       -0.20181843, -0.81009494]), array([ 5., -8., -2., 11.,  4., -2., -4.]))
test:

arr= [ 0.67  1.67  2.67  3.67  4.67  5.67  6.67  7.67  8.67  9.67 10.67 11.67
 12.67 13.67 14.67] 

np.modf(arr)= (array([0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 0.67, 0.67,
       0.67, 0.67, 0.67, 0.67]), array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])) 



In [75]:
?np.modf

Call signature:  np.modf(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'modf'>
File:            d:\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
modf(x[, out1, out2], / [, out=(None, None)], *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the fractional and integral parts of an array, element-wise.

The fractional and integral parts are negative if the given number is
negative.

Parameters
----------
x : array_like
    Input array.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` a