In [237]:
from numpy.random import randn #产生正态随机数的函数
import numpy as np #简便书写

In [238]:
np.array([3.4, 5.5])#生成array 数据的函数

array([3.4, 5.5])

In [239]:
data = randn(2,3)
print(data)
print(data.shape) #输出array格式的数据的维数
print(data.dtype) #输出array格式的的数据的类别
b = [[2,]]
np.array(b).shape #说明空的会被省略掉

[[-0.42994715  0.20095737  1.56722785]
 [ 1.51359402 -0.13347853  0.91514275]]
(2, 3)
float64


(1, 1)

In [240]:
a=np.array([1,2,3])
b=np.array([[1,]])
c=np.array([[1,0,0],[0,1,2]])
print(a,a.shape,a.dtype,end='\n\n')
print(b,b.shape,b.dtype,end='\n\n')
print(c,c.shape,c.dtype,end='\n\n')

[1 2 3] (3,) int32

[[1]] (1, 1) int32

[[1 0 0]
 [0 1 2]] (2, 3) int32



In [241]:
print(np.arange(15),end='\n\n') #输出等差数列，默认值0-15，不包含mxa=15，默认步长为1
print(np.arange(2,15),end='\n\n') #输出等差数列，从2-15，不包含15，默认步长为1
print(np.arange(2,15,2),end='\n\n') #输出等差数列，从2-15，不包含15，步长设定为2
print(np.arange(2,15,1.5),end='\n\n') #步长设定为1.5

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 2  4  6  8 10 12 14]

[ 2.   3.5  5.   6.5  8.   9.5 11.  12.5 14. ]



In [242]:
print(np.linspace(0,1,11),end='\n\n')#从0-11，不包含11，设定一共有11个
print(np.linspace(0,1,11, endpoint = False), end='\n\n')
print(np.linspace(0,1,11, endpoint = True), end='\n\n')#可以设置是否包含max
print(np.linspace(0,1,12),end='\n\n')

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]



In [243]:
data1=[6,7.8,8.9,33]
arr1=np.array(data1)
print(arr1,arr1.shape,arr1.dtype)

[ 6.   7.8  8.9 33. ] (4,) float64


In [244]:
data2=[[1,2,3.0,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2,arr2.shape,arr2.dtype)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]] (2, 4) float64


In [245]:
#使用reshape来改变维数
print(arr2,arr2.shape,arr2.dtype,end='\n\n')
b=arr2.reshape((1,8))
print(b,b.shape,b.dtype,end='\n\n')
b=arr2.reshape((4,2))
print(b,b.shape,b.dtype,end='\n\n')


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]] (2, 4) float64

[[1. 2. 3. 4. 5. 6. 7. 8.]] (1, 8) float64

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]] (4, 2) float64



In [246]:
a=np.zeros(10,dtype='int')
print(a,a.shape,a.dtype)
a=np.zeros(10,dtype='float')
print(a,a.shape,a.dtype)

[0 0 0 0 0 0 0 0 0 0] (10,) int32
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] (10,) float64


In [247]:
b=np.ones((2,3),dtype='int')
print(b,b.shape,b.dtype)
b=np.ones((2,3),dtype='float')
print(b,b.shape,b.dtype)

[[1 1 1]
 [1 1 1]] (2, 3) int32
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3) float64


In [248]:
c=np.identity(2)#单位矩阵(方阵)
print(c,c.shape,c.dtype,end='\n\n')
d=np.eye(4,9)
print(d,d.shape,d.dtype)

[[1. 0.]
 [0. 1.]] (2, 2) float64

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]] (4, 9) float64


In [249]:
arr = np.array([1,2,3,4,5],dtype=np.int32)
print(arr,arr.shape,arr.dtype)

[1 2 3 4 5] (5,) int32


In [250]:
#使用astype去修改类型
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.shape,float_arr.dtype)

[1. 2. 3. 4. 5.] (5,) float64


In [251]:
arr=np.array([3.7,1.2,0.5,12.7,5.6])
c=arr.astype(np.int32)
print(c,c.shape,c.dtype)

[ 3  1  0 12  5] (5,) int32


In [252]:
c=numeric_strings = np.array(['1.25', '42'],dtype=str)
print(c,c.shape,c.dtype)
c=c.astype(float)
print(c,c.shape,c.dtype)

['1.25' '42'] (2,) <U4
[ 1.25 42.  ] (2,) float64


In [253]:
arr=np.array(([1,2,3],[4,5,6]),dtype=float)
print(arr,end='\n\n')
print(arr*arr,end='\n\n')#对应元素相乘
print(arr*arr-arr,end='\n\n')
print(1/arr,end='\n\n')
print(arr*2,end='\n\n')
print(arr**2,end='\n\n')#对应元素平方

[[1. 2. 3.]
 [4. 5. 6.]]

[[ 1.  4.  9.]
 [16. 25. 36.]]

[[ 0.  2.  6.]
 [12. 20. 30.]]

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

[[ 2.  4.  6.]
 [ 8. 10. 12.]]

[[ 1.  4.  9.]
 [16. 25. 36.]]



In [254]:
arr=np.arange(10)
print(arr,arr.shape,arr.dtype)
print(arr[5:8])
arr[5:8] = 12
print(arr,arr.shape,arr.dtype)

[0 1 2 3 4 5 6 7 8 9] (10,) int32
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9] (10,) int32


In [255]:
arr=np.arange(10)
arr_slice=arr[5:8]
print(id(arr_slice), id(arr[5:8]),)
print(arr_slice is arr[5:8],'\n',arr_slice == arr[5:8] )
arr_slice[1]=12345
print(arr,'\n', arr_slice)

1923494384176 1923495459984
False 
 [ True  True  True]
[    0     1     2     3     4     5 12345     7     8     9] 
 [    5 12345     7]


原因：
> object（对象） 与 location（地址） 并不相同
+ 一个对象可以是一个指针，例如对象A是个指针，它的内容是->B，其中B是一个存储空间；C也可以是个指针，内容也是->B，这时候它们是两个不同的对象，指向同一个存储空间
> 但实际上，切片slice，只是创造了一个视图，其实指向的地址还是不一样

In [256]:
print(arr,'\n',arr_slice)
arr_slice[:]=64
print(arr,'\n',arr_slice)

[    0     1     2     3     4     5 12345     7     8     9] 
 [    5 12345     7]
[ 0  1  2  3  4 64 64 64  8  9] 
 [64 64 64]


In [257]:
a_list=list(range(10))
list_slice=a_list[5:8]
print(a_list is list_slice)
list_slice[1] = 12345
print(a_list, '\n', list_slice)

False
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
 [5, 12345, 7]


In [258]:
a=[1,2,3,[1,2]]
b=a[3][1]
print(b is a[3][1])
b=1000
print(a,'\n',b)

True
[1, 2, 3, [1, 2]] 
 1000


In [259]:
import copy
c=copy.deepcopy(a)
print(a is c, a==c)

False True


In [260]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d,arr2d.shape,arr2d.dtype,end='\n\n')
print(arr2d,'\n\n',arr2d[0],'\n\n',arr2d[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) int32

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [1 2 3] 

 2


In [261]:
print(arr2d,end='\n\n')
print(arr2d[:][0] , '\n\n', arr2d[:,0],end='\n\n')
print(arr2d[:][0]==arr2d[:,0], arr2d[:][0] is arr2d[:,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3] 

 [1 4 7]

[ True False False] False


+ arr2d[:][0] is equivalent to arr2d[0] instead of arr2d[:,0]

In [262]:
#二维数组切片也传输地址
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d,end='\n\n')
b = arr2d[2]
print(b,b is arr2d[2],end='\n\n')
arr2d[2] = 3
print('arr2d[2]=',arr2d[2],'\n\n','arr2d=\n',arr2d,end='\n\n')
#二维数组的切片一定会传地址
c=arr2d[0][:2]
print(c is arr2d[0][:2], c, end='\n\n')
arr2d[0][:2]=1000
print('arr2d[0][:2]=',arr2d[0][:2],'\n','arr2d=\n',arr2d,end='\n\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[7 8 9] False

arr2d[2]= [3 3 3] 

 arr2d=
 [[1 2 3]
 [4 5 6]
 [3 3 3]]

False [1 2]

arr2d[0][:2]= [1000 1000] 
 arr2d=
 [[1000 1000    3]
 [   4    5    6]
 [   3    3    3]]



In [263]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d,'\n\n',arr3d.shape,'\n\n',arr3d.dtype)
print('arr3d[0]=',arr3d[0])
print('arr3d[0][0]=',arr3d[0][0])
print('arr3d[0][0][0]=',arr3d[0][0][0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

 (2, 2, 3) 

 int32
arr3d[0]= [[1 2 3]
 [4 5 6]]
arr3d[0][0]= [1 2 3]
arr3d[0][0][0]= 1


+ 数组拷贝
> 要生成新的对象(传递数值)，而不是传递地址，需要用到copy函数

In [264]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d,arr2d.shape,arr2d.dtype,end='\n\n')

old_values=arr2d.copy()
old_1=copy.deepcopy(arr2d)
print(old_values)

arr2d[0][:]=999
print(arr2d,'\n',old_values,'\n',old_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) int32

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[999 999 999]
 [  4   5   6]
 [  7   8   9]] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [265]:
print(arr)
print(arr[1:6],'\n')

print(arr2d)
print(arr2d[:2],'\n')

print(arr2d[1, :2],'\n')

arr2d[:2 , 1: ]=0
print(arr2d)

[ 0  1  2  3  4 64 64 64  8  9]
[ 1  2  3  4 64] 

[[999 999 999]
 [  4   5   6]
 [  7   8   9]]
[[999 999 999]
 [  4   5   6]] 

[4 5] 

[[999   0   0]
 [  4   0   0]
 [  7   8   9]]


In [266]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = randn(7,4)
print(names,'\n\n',data,'\n')

print(names == 'Bob','\n') #返回的逻辑判断是对所有元素逐个判断之后合并起来的array变量
print(data[names == 'Bob'],'\n')#输出的是取了True的行，其他都没有输出
print(data[names == 'Bob',2:],'\n')#第三列到最后
print(data[names == 'Bob',3:],'\n')#第四列

print(names != 'Bob')
print(data[names != 'Bob'],'\n')

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] 

 [[ 2.00356037 -0.48959041 -0.87164675  0.51845331]
 [-0.70049674 -1.79265863 -0.15598787  0.5171986 ]
 [ 2.68404642 -0.32719274 -0.64353083  0.40603448]
 [-0.31549991 -0.81249671 -1.00176253 -0.23023844]
 [ 1.26854787  2.79005299 -0.21017096  0.16679061]
 [ 0.17642904 -0.73489387 -0.41677191 -1.23605898]
 [ 0.51474135  0.00741902  0.56536301 -0.7813853 ]] 

[ True False False  True False False False] 

[[ 2.00356037 -0.48959041 -0.87164675  0.51845331]
 [-0.31549991 -0.81249671 -1.00176253 -0.23023844]] 

[[-0.87164675  0.51845331]
 [-1.00176253 -0.23023844]] 

[[ 0.51845331]
 [-0.23023844]] 

[False  True  True False  True  True  True]
[[-0.70049674 -1.79265863 -0.15598787  0.5171986 ]
 [ 2.68404642 -0.32719274 -0.64353083  0.40603448]
 [ 1.26854787  2.79005299 -0.21017096  0.16679061]
 [ 0.17642904 -0.73489387 -0.41677191 -1.23605898]
 [ 0.51474135  0.00741902  0.56536301 -0.7813853 ]] 



In [267]:
mask = (names == 'Bob') | (names == 'Will')  # 还有&
print(mask,'\n')
print(data[mask],'\n')

[ True False  True  True  True False False] 

[[ 2.00356037 -0.48959041 -0.87164675  0.51845331]
 [ 2.68404642 -0.32719274 -0.64353083  0.40603448]
 [-0.31549991 -0.81249671 -1.00176253 -0.23023844]
 [ 1.26854787  2.79005299 -0.21017096  0.16679061]] 



In [268]:
print(data,'\n')
print(data < 0 ,'\n')

data[data<0] = 0
print ( data,'\n')

[[ 2.00356037 -0.48959041 -0.87164675  0.51845331]
 [-0.70049674 -1.79265863 -0.15598787  0.5171986 ]
 [ 2.68404642 -0.32719274 -0.64353083  0.40603448]
 [-0.31549991 -0.81249671 -1.00176253 -0.23023844]
 [ 1.26854787  2.79005299 -0.21017096  0.16679061]
 [ 0.17642904 -0.73489387 -0.41677191 -1.23605898]
 [ 0.51474135  0.00741902  0.56536301 -0.7813853 ]] 

[[False  True  True False]
 [ True  True  True False]
 [False  True  True False]
 [ True  True  True  True]
 [False False  True False]
 [False  True  True  True]
 [False False False  True]] 

[[2.00356037 0.         0.         0.51845331]
 [0.         0.         0.         0.5171986 ]
 [2.68404642 0.         0.         0.40603448]
 [0.         0.         0.         0.        ]
 [1.26854787 2.79005299 0.         0.16679061]
 [0.17642904 0.         0.         0.        ]
 [0.51474135 0.00741902 0.56536301 0.        ]] 



In [269]:
data [ names != 'Joe'] = 7
print(data)

[[7.         7.         7.         7.        ]
 [0.         0.         0.         0.5171986 ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [7.         7.         7.         7.        ]
 [0.17642904 0.         0.         0.        ]
 [0.51474135 0.00741902 0.56536301 0.        ]]
